import type {Command,Snapshot} from './types';
type ModelContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations?:{readOnlyHint:boolean};execute:(input:unknown)=>Promise<unknown>},options:{signal:AbortSignal})=>void|Promise<void>};
export function registerSimulationTools(dispatch:(c:Command)=>Promise<Snapshot>){const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return()=>{};const controller=new AbortController();
 const summarize=(s:Snapshot)=>({time:s.state.time,paused:s.paused,speed:s.speed,workers:s.state.ants.filter(a=>a.task!=='queen').length,brood:s.state.brood.length,resourceSources:s.state.resources.length,obstacles:s.state.obstacles.length,encounters:s.state.encounters,visitors:s.state.enemies,defending:s.state.ants.filter(a=>a.task==='defending').length,retreating:s.state.ants.filter(a=>a.task==='retreating').length,stores:s.state.stores,settings:s.state.settings,seed:s.state.seed,queenAlive:s.state.ants.some(a=>a.task==='queen'),excavated:s.state.excavated,depositedSoil:s.state.depositedSoil,removedWaste:s.state.removedWaste,births:s.state.births,deaths:s.state.deaths,stepMs:s.stepMs});
 const register=(tool:Parameters<ModelContext['registerTool']>[0])=>{try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}};
 register({name:'read_ant_colony',description:'Read current colony metrics, settings, and playback state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>summarize(await dispatch({type:'snapshot'}))});
 register({name:'set_colony_playback',description:'Pause or resume the current colony and optionally set speed to 1, 2, 4, or 8.',inputSchema:{type:'object',properties:{paused:{type:'boolean'},speed:{type:'number',enum:[1,2,4,8]}},required:['paused'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input)=>{if(!input||typeof input!=='object')throw new Error('Expected playback settings.');const p=input as {paused:boolean;speed?:number};if(typeof p.paused!=='boolean'||p.speed!==undefined&&![1,2,4,8].includes(p.speed))throw new Error('Invalid playback settings.');if(p.speed!==undefined)await dispatch({type:'speed',speed:p.speed});return summarize(await dispatch({type:'pause',paused:p.paused}));}});
 register({name:'set_colony_encounters',description:'Enable optional surface spiders or rival food foragers, or change encounter frequency. Current visitors withdraw when disabled.',inputSchema:{type:'object',properties:{spiderEncounters:{type:'boolean'},rivalEncounters:{type:'boolean'},encounterFrequency:{type:'number',minimum:.25,maximum:4}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>summarize(await dispatch({type:'settings',settings:input as Partial<import('./types').Settings>}))});
 register({name:'place_colony_resource',description:'Place carbohydrate food, protein food, water, or a rock on the surface, or erase a nearby resource or rock.',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['carbohydrate','protein','water','obstacle','erase']},x:{type:'number',minimum:30,maximum:1370},y:{type:'number',minimum:30,maximum:870}},required:['kind','x','y'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||typeof input!=='object')throw new Error('Expected a resource and coordinates.');return summarize(await dispatch({...input,type:'place'} as Command));}});
 return()=>controller.abort();
}
