'use client';
import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowUpRight, ChevronRight, CircleHelp, Crosshair, Focus, Globe2, Layers3, Minus, MousePointer2, Orbit, Pause, Play, Plus, Rocket, RotateCcw, SkipForward, SlidersHorizontal, Sparkles, Sun, Target, Trash2, X } from 'lucide-react';
import HubNavigation, { SimulatorId } from '@/components/hub-navigation';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarTrigger } from '@/components/ui/sidebar';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { Slider } from '@/components/ui/slider';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import SolarCanvas, { SolarControls } from './solar-canvas';
import { AU_KM, Body, G, KM_S, MAX_DAY, MIN_DAY, MOONS, PLANETS, Scenario, SolarEngine, dateDay, dayDate, length, sub } from '@/lib/solar/engine';
import './solar.css';
import { registerSolarTools } from '@/lib/solar/webmcp';
const scenarios:{id:Scenario;title:string;description:string;number:string}[]=[
 {id:'earth-speed',title:'A faster Earth',description:'Increase Earth’s speed by 35% and watch its orbit change.',number:'01'},
 {id:'jupiter-comet',title:'An encounter with Jupiter',description:'Send a comet near the gas giant and follow its deflection.',number:'02'},
 {id:'binary',title:'Two suns, one planet',description:'Explore a planet orbiting a pair of stars.',number:'03'},
 {id:'mars-launch',title:'The road to Mars',description:'Explore a transfer attempt. Timing matters as much as speed.',number:'04'},
];
export default function SolarLab({active,onNavigate}:{active:boolean;onNavigate:(id:SimulatorId)=>void}){
 const [engine]=useState(()=>new SolarEngine());const [,refresh]=useState(0);const controls=useRef<SolarControls|null>(null);
 const [selected,setSelected]=useState<string|null>('earth');const [follow,setFollow]=useState<string|null>(null);const [view,setView]=useState<'3d'|'top'>('3d');const [tool,setTool]=useState<'select'|'probe'|'comet'>('select');const [orbits,setOrbits]=useState(true);const [labels,setLabels]=useState(true);const [vectors,setVectors]=useState(false);const [gravity,setGravity]=useState(false);const [trueScale,setTrueScale]=useState(false);const [moons,setMoons]=useState(true);const [help,setHelp]=useState(false);const [experiments,setExperiments]=useState(false);const [fps,setFps]=useState(0);const [error,setError]=useState('');const [confirm,setConfirm]=useState<'reference'|'reset'|Scenario|null>(null);const [date,setDate]=useState(dayDate(engine.day));const [massFactor,setMassFactor]=useState(1);const [velocityFactor,setVelocityFactor]=useState(1.2);const [positionX,setPositionX]=useState(engine.bodies.find(b=>b.id==='earth')!.p[0].toFixed(4));const [positionY,setPositionY]=useState(engine.bodies.find(b=>b.id==='earth')!.p[1].toFixed(4));
 useEffect(()=>active?registerSolarTools(engine,()=>refresh(n=>n+1)):undefined,[active,engine]);
 const sync=()=>{refresh(n=>n+1);};const body=engine.bodies.find(b=>b.id===selected);const sun=engine.bodies.find(b=>b.id==='sun');const parent=engine.bodies.find(b=>b.id===(body?.parent??'sun'));const distance=body&&sun?length(sub(body.p,sun.p)):null;const speed=body?length(body.v)*KM_S:0;
 const select=(id:string,focus=false)=>{setTool('select');setSelected(id);engine.selected=id;engine.history=[];setMassFactor(1);setVelocityFactor(1.2);const b=engine.bodies.find(b=>b.id===id);if(b){setPositionX(b.p[0].toFixed(4));setPositionY(b.p[1].toFixed(4));}if(focus){setFollow(id);controls.current?.focus(id);}sync();};
 const attempt=(fn:()=>void)=>{try{fn();setError('');sync();}catch(e){setError((e as Error).message);}};
 const prepareTool=(value:'select'|'probe'|'comet')=>{setTool(value);if(value!=='select'){engine.experiment();engine.paused=true;setFollow(null);setView('top');setError('');sync();}};
 const reset=(action:'reference'|'reset'|Scenario)=>{attempt(()=>{if(action==='reference'||action==='reset'){engine.reset(Math.max(MIN_DAY,Math.min(MAX_DAY-1,engine.day)));setDate(dayDate(engine.day));setSelected('earth');}else{engine.scenario(action);setSelected(engine.selected);}setFollow(null);setTool('select');setView('3d');controls.current?.fit(action==='binary');if(action==='binary')controls.current?.zoom(1.8);if(action==='jupiter-comet'){const j=engine.bodies.find(b=>b.id==='jupiter');if(j){setFollow(j.id);controls.current?.focus(j.id);controls.current?.zoom(.025);}}setExperiments(false);});};
 const requestReset=(action:'reference'|'reset'|Scenario)=>{if(engine.mode==='experiment')setConfirm(action);else reset(action);};
 useEffect(()=>{if(!active)return;const key=(e:KeyboardEvent)=>{const t=e.target as HTMLElement;if(t.closest('input,textarea,button,[role="dialog"],[role="alertdialog"],[role="slider"],[role="combobox"],[role="tab"],[contenteditable="true"]'))return;if(e.code==='Space'){e.preventDefault();engine.paused=!engine.paused;refresh(n=>n+1);}if(e.key==='Escape'){setTool('select');setSelected(null);setFollow(null);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[engine,active]);
 const baseMass=body?.id==='sun'?1:PLANETS.find(p=>p.id===body?.id)?.mass??MOONS.find(p=>p.id===body?.id)?.mass??body?.mass??1;
 return <SidebarProvider style={{'--sidebar-width':'264px'} as React.CSSProperties} className="app-shell solar-shell"><Sidebar className="observatory-sidebar"><SidebarHeader className="brand"><div className="brand-symbol"><Orbit size={23}/></div><div><strong>simulation<span>hub</span></strong><small>A SPACE FOR CURIOSITY</small></div><SidebarTrigger className="mobile-sidebar-close" aria-label="Close settings"/></SidebarHeader><SidebarContent><HubNavigation current="solar" onNavigate={onNavigate}/><div className="sidebar-divider"/>
 <div className="sidebar-section solar-mode"><div className="section-title"><SlidersHorizontal size={15}/><span>Laboratory mode</span></div><Tabs value={engine.mode} onValueChange={v=>v==='experiment'?attempt(()=>engine.experiment()):requestReset('reference')}><TabsList className="view-tabs solar-mode-tabs"><TabsTrigger value="explore">Explore</TabsTrigger><TabsTrigger value="experiment">Experiment</TabsTrigger></TabsList></Tabs><p className="solar-sidebar-note">{engine.mode==='explore'?'Follow the planets using approximate reference orbits.':'Change the system and let gravity take over.'}</p></div><div className="sidebar-divider"/>
 <div className="sidebar-section solar-objects"><div className="section-title"><Globe2 size={15}/><span>Objects</span><span className="solar-count">{engine.bodies.length}</span></div><div className="solar-object-list">{engine.bodies.filter(b=>b.kind!=='moon').map(b=><button key={b.id} className={selected===b.id?'selected':''} onClick={()=>select(b.id,true)} aria-label={`Inspect ${b.name}`} aria-pressed={selected===b.id}><span className={`body-dot ${b.kind}`} style={{'--body-color':b.color} as React.CSSProperties}/><span>{b.name}</span>{b.kind==='star'?<Sun size={12}/>:<ChevronRight size={12}/>}</button>)}</div>{moons&&<details className="solar-moon-list"><summary>Major moons <span>{engine.bodies.filter(b=>b.kind==='moon').length}</span></summary>{engine.bodies.filter(b=>b.kind==='moon').map(b=><button key={b.id} onClick={()=>select(b.id,true)} aria-label={`Inspect ${b.name}`}><span className="body-dot" style={{'--body-color':b.color} as React.CSSProperties}/>{b.name}<small>{engine.bodies.find(p=>p.id===b.parent)?.name??'Independent'}</small></button>)}</details>}</div><div className="sidebar-divider"/>
 <div className="sidebar-section"><div className="section-title"><Layers3 size={15}/><span>View layers</span></div><Layer label="Orbits & trails" value={orbits} onChange={setOrbits}/><Layer label="Object labels" value={labels} onChange={setLabels}/><Layer label="Major moons" value={moons} onChange={setMoons}/><Layer label="Velocity arrows" value={vectors} onChange={setVectors}/><Layer label="Gravity direction" value={gravity} onChange={setGravity}/><Layer label="True planet sizes" value={trueScale} onChange={setTrueScale}/></div><div className="sidebar-divider"/>
 <div className="sidebar-section solar-date"><label htmlFor="reference-date">Reference date</label><input id="reference-date" type="date" value={date} min="1800-01-01" max="2049-12-31" disabled={engine.mode==='experiment'} onChange={e=>setDate(e.target.value)}/><button className="button secondary" disabled={engine.mode==='experiment'} onClick={()=>attempt(()=>{engine.reset(dateDay(date));engine.paused=true;setFollow(null);setSelected('earth');})}>Go to date</button></div>
 </SidebarContent><SidebarFooter className="sidebar-bottom"><button onClick={()=>setHelp(true)}><CircleHelp size={17}/>Lab notes<span>↗</span></button><div className="version-line"><span>SOLAR SYSTEM LAB</span><span>02</span></div></SidebarFooter></Sidebar>
 <main className="workspace solar-workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>Simulations</span><ChevronRight size={14}/><strong>Solar System Lab</strong></div><button className="button secondary solar-experiments-button" aria-label="Experiments" onClick={()=>setExperiments(true)}><Sparkles size={15}/><span>Experiments</span></button></header><div className="page-heading"><div><div className="title-row"><h1>A little closer <span>to the cosmos.</span></h1><span className="species-tag solar-mode-tag">{engine.mode==='explore'?'REFERENCE ORBITS':'GRAVITY SANDBOX'}</span></div><p>Explore our neighborhood. Discover what keeps it in motion.</p></div><button className="icon-button" aria-label="About Solar System Lab" onClick={()=>setHelp(true)}><CircleHelp size={19}/></button></div>
 {error&&<div className="error-banner" role="alert">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={14}/></button></div>}
 <section className="simulation-panel solar-panel" aria-label="Solar System Lab"><div className="world-topbar solar-topbar"><Tabs value={view} onValueChange={v=>{setView(v as '3d'|'top');setTool('select');}}><TabsList className="view-tabs"><TabsTrigger value="3d"><Orbit size={15}/>3D view</TabsTrigger><TabsTrigger value="top"><Layers3 size={15}/>Orbital map</TabsTrigger></TabsList></Tabs><div className="playback"><span className="solar-date-display">{dayDate(engine.day)}</span><button className="icon-button pause-button" aria-label={engine.paused?'Play Solar System':'Pause Solar System'} onClick={()=>{engine.paused=!engine.paused;sync();}}>{engine.paused?<Play size={15}/>:<Pause size={15}/>}</button><button className="icon-button" aria-label="Advance one day" title="Advance one day; close encounters may advance less" onClick={()=>{engine.paused=false;engine.tick(1,1500);engine.paused=true;sync();}}><SkipForward size={15}/></button><Select value={String(engine.speed)} onValueChange={v=>{engine.speed=Number(v);sync();}}><SelectTrigger aria-label="Solar simulation speed" className="speed-select"><SelectValue/></SelectTrigger><SelectContent>{[.1,1,5,10,30,100,365].map(v=><SelectItem key={v} value={String(v)}>{v} d / s</SelectItem>)}</SelectContent></Select><button className="icon-button" aria-label="Reset Solar System" onClick={()=>requestReset('reset')}><RotateCcw size={15}/></button></div></div>
 <div className="world-area solar-world"><SolarCanvas engine={engine} active={active} display={{orbits,labels,vectors,gravity,trueScale,moons,follow,selected}} view={view} tool={tool} controls={controls} onSelect={select} onPan={()=>setFollow(null)} onError={setError} onChange={f=>{setFps(f);if(selected&&!engine.bodies.some(b=>b.id===selected)){setSelected(engine.bodies.some(b=>b.id===engine.selected)?engine.selected:null);setFollow(null);}refresh(n=>n+1);}}/>
 <div className="solar-observation"><span className={engine.paused?'':'solar-live'}/>{engine.paused?'TIME PAUSED':'IN MOTION'}<span className="solar-observation-divider"/>{engine.mode==='explore'?'OUR SOLAR SYSTEM':'EXPERIMENTAL SYSTEM'}</div><div className="solar-framing"><button onClick={()=>controls.current?.fit(false)}>Inner system</button><button onClick={()=>controls.current?.fit(true)}>Full system</button></div>
 <div className="world-tools solar-tools" role="toolbar" aria-label="Space tools"><button aria-label="Select a body" aria-pressed={tool==='select'} className={tool==='select'?'active':''} onClick={()=>prepareTool('select')} title="Select"><MousePointer2 size={18}/></button><button aria-label="Launch a probe" aria-pressed={tool==='probe'} className={tool==='probe'?'active':''} onClick={()=>prepareTool('probe')} title="Launch a probe"><Rocket size={18}/></button><button aria-label="Launch a comet" aria-pressed={tool==='comet'} className={tool==='comet'?'active':''} onClick={()=>prepareTool('comet')} title="Launch a comet"><Sparkles size={18}/></button></div>
 {body&&<aside className="solar-inspector" aria-label={`${body.name} inspector`}><div className="solar-inspector-header"><span className="solar-kicker">{body.kind==='moon'?`MOON OF ${parent?.name.toUpperCase()??'REMOVED BODY'}`:body.kind.toUpperCase()}</span><button className="icon-button" aria-label="Close body inspector" onClick={()=>setSelected(null)}><X size={15}/></button></div><div className="solar-body-title"><span className="inspector-planet" style={{'--body-color':body.color} as React.CSSProperties}/><h2>{body.name}</h2></div><p className="solar-body-description">{PLANETS.find(p=>p.id===body.id)?.description??(body.kind==='star'?'The gravitational heart of this system.':body.kind==='moon'?'A close companion. Zoom in to explore its orbit.':'A custom object following the gravity of this system.')}</p><dl className="solar-values"><div><dt>Speed</dt><dd>{speed.toFixed(2)} <span>km/s</span></dd></div><div><dt>{body.kind==='moon'?'From parent':'From Sun'}</dt><dd>{body.kind==='moon'&&parent?`${Math.round(length(sub(body.p,parent.p))*AU_KM).toLocaleString()} km`:distance!==null?`${distance.toFixed(3)} AU`:'—'}</dd></div><div><dt>Mass</dt><dd>{body.kind==='star'?`${body.mass.toFixed(3)} M☉`:`${(body.mass/3.0035e-6).toLocaleString(undefined,{maximumSignificantDigits:4})} M⊕`}</dd></div><div><dt>Radius</dt><dd>{body.radius<1?(body.radius*1000).toLocaleString(undefined,{maximumFractionDigits:1}):body.radius.toLocaleString(undefined,{maximumFractionDigits:1})} <span>{body.radius<1?'m':'km'}</span></dd></div></dl><button className={`button solar-follow ${follow===body.id?'following':'secondary'}`} onClick={()=>{if(follow===body.id)setFollow(null);else{setFollow(body.id);controls.current?.focus(body.id);}}}><Target size={14}/>{follow===body.id?'Following · stop':'Follow & focus'}<ArrowUpRight size={13}/></button>
 {engine.mode==='experiment'?<details className="solar-body-edit" onToggle={e=>{if(e.currentTarget.open){setPositionX(body.p[0].toFixed(5));setPositionY(body.p[1].toFixed(5));}}}><summary><SlidersHorizontal size={14}/>Edit this body</summary><label>Mass multiplier <output>{massFactor.toFixed(1)}×</output></label><Slider aria-label="Body mass multiplier" value={[massFactor]} min={.1} max={10} step={.1} onValueChange={v=>setMassFactor(v[0])}/><button className="button secondary" onClick={()=>attempt(()=>engine.setMass(body.id,baseMass*massFactor))}>Apply mass</button><label>Current speed × <output>{velocityFactor.toFixed(2)}</output></label><Slider aria-label="Body velocity multiplier" value={[velocityFactor]} min={0} max={2} step={.05} onValueChange={v=>setVelocityFactor(v[0])}/><button className="button secondary" onClick={()=>attempt(()=>engine.velocity(body.id,velocityFactor))}>Apply velocity</button><div className="solar-position"><label>X · AU<input aria-label="Body X position in AU" type="number" step=".01" min="-100" max="100" value={positionX} onChange={e=>setPositionX(e.target.value)}/></label><label>Y · AU<input aria-label="Body Y position in AU" type="number" step=".01" min="-100" max="100" value={positionY} onChange={e=>setPositionY(e.target.value)}/></label></div><button className="button secondary" onClick={()=>attempt(()=>{if(!positionX.trim()||!positionY.trim())throw new Error('Enter both coordinates.');engine.move(body.id,[Number(positionX),Number(positionY),body.p[2]]);})}>Move body</button><button className="button solar-remove" onClick={()=>attempt(()=>{engine.remove(body.id);setSelected(null);setFollow(null);})}><Trash2 size={13}/>Remove {body.name}</button></details>:<button className="solar-edit-link" onClick={()=>attempt(()=>engine.experiment())}>Experiment with this body <ArrowUpRight size={13}/></button>}
 </aside>}
 <div className="world-hint solar-hint">{tool==='select'?<><MousePointer2 size={13}/>{follow?`Following ${engine.bodies.find(b=>b.id===follow)?.name??'object'} · drag to release`:'Drag to explore · Shift-drag to rotate'}</>:<>Drag to launch a {tool} · arrow sets velocity · preview is approximate</>}</div><div className="zoom-controls solar-zoom"><button aria-label="Zoom in on Solar System" onClick={()=>controls.current?.zoom(1.6)}><Plus size={17}/></button><button aria-label="Zoom out of Solar System" onClick={()=>controls.current?.zoom(1/1.6)}><Minus size={17}/></button><span/><button aria-label="Fit Solar System" onClick={()=>controls.current?.fit(true)}><Focus size={17}/></button></div><span className="solar-scale-note">{trueScale?'TRUE PLANET SIZES · distances to scale':'PLANETS ENLARGED · distances to scale'}</span>
 </div><div className="solar-metrics"><div><span className="solar-kicker">SYSTEM</span><strong>{engine.bodies.length}<small>objects</small></strong><p>{engine.mode==='explore'?'Sun, planets & selected moons':'Newtonian gravity · physical collisions'}</p></div><div><span className="solar-kicker">{body?`${body.name.toUpperCase()} SPEED`:'SELECT A BODY'}</span><strong>{body?speed.toFixed(2):'—'}<small>km/s</small></strong><p>{engine.mode==='explore'?'Approximate JPL reference model':'Speed in the simulation frame'}</p></div><div className="solar-chart"><span className="solar-kicker">SPEED OVER TIME</span><Sparkline data={engine.history.map(h=>h.speed)}/><p>{engine.history.length>1?`${(engine.history.at(-1)!.day-engine.history[0].day).toFixed(1)} simulated days`:'Collecting observations…'}</p></div></div></section>
 <footer className="workspace-footer solar-footer"><span>{engine.events[0]??(engine.mode==='explore'?'JPL orbital elements · approximate positions':'Edits apply to this sandbox session')}{engine.events[0]&&<button aria-label="Dismiss event" onClick={()=>{engine.events.shift();sync();}}><X size={12}/></button>}</span><span>{fps} FPS <i>·</i>Space to pause</span></footer></main>
 <Dialog open={experiments} onOpenChange={setExperiments}><DialogContent className="solar-dialog"><DialogHeader><DialogTitle>A change worth watching.</DialogTitle><DialogDescription>Choose an experiment. Each starts paused with its own setup.</DialogDescription></DialogHeader><div className="solar-scenario-list">{scenarios.map(s=><button key={s.id} onClick={()=>requestReset(s.id)}><span>{s.number}</span><div><h3>{s.title}</h3><p>{s.description}</p></div><ArrowUpRight size={19}/></button>)}</div></DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="solar-dialog solar-notes"><DialogHeader><DialogTitle>Inside Solar System Lab</DialogTitle><DialogDescription>Two ways to explore the same neighborhood.</DialogDescription></DialogHeader><h3>Explore the reference system</h3><p>Planets follow JPL’s approximate Keplerian elements for 1800–2050. These are calculated positions, not a live Horizons feed. Earth uses the Earth–Moon barycenter approximation. Selected moons use illustrative circular orbits with approximate periods and phases.</p><h3>Experiment with gravity</h3><p>The sandbox begins from those positions and velocities. Bodies then interact through Newtonian gravity. Collisions merge bodies at their physical radii; enlarged display sizes do not affect physics. Relativity, tides, atmospheric drag, and fragmentation are omitted.</p><p>Fast playback may run slower during close encounters to maintain smaller calculation steps. A launch preview treats other bodies as stationary, so it is a rough guide. Drag length sets launch speed: one AU equals about 34.6 km/s.</p><h3>Find your way around</h3><p>Drag to pan, Shift-drag or right-drag to rotate, and scroll or pinch to zoom. Use the object list to focus on distant planets and moons. Arrow keys pan the focused canvas, +/− zoom, Enter selects the next body, and Space pauses time.</p><p>Planet surfaces are stylized. Distances stay to scale; planets are enlarged unless true sizes are enabled. Velocity arrow length is scaled for the current view; the gravity arrow shows direction only.</p><p>Switching simulators pauses the inactive world and keeps its session. Solar experiments are held in this tab and reset on a page reload; ant saves remain separate.</p><div className="solar-sources"><a href="https://ssd.jpl.nasa.gov/planets/approx_pos.html" target="_blank" rel="noreferrer">JPL orbital elements ↗</a><a href="https://ssd.jpl.nasa.gov/astro_par.html" target="_blank" rel="noreferrer">JPL physical constants ↗</a></div></DialogContent></Dialog>
 <AlertDialog open={confirm!==null} onOpenChange={open=>{if(!open)setConfirm(null);}}><AlertDialogContent className="solar-dialog"><AlertDialogHeader><AlertDialogTitle>Replace this experiment?</AlertDialogTitle><AlertDialogDescription>Your current solar edits and added objects will be replaced. The ant colony is kept.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep experiment</AlertDialogCancel><AlertDialogAction onClick={()=>{if(confirm)reset(confirm);setConfirm(null);}}>Replace system</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>;
}
function Layer({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){return <label className="layer-toggle solar-layer"><span>{label}</span><Switch aria-label={label} checked={value} onCheckedChange={onChange}/></label>;}
function Sparkline({data}:{data:number[]}){const min=Math.min(...data),max=Math.max(...data),range=max-min||Math.max(max*.02,1);const points=data.map((v,i)=>`${i/Math.max(1,data.length-1)*200},${35-(v-min)/range*30}`).join(' ');return <svg viewBox="0 0 200 40" role="img" aria-label="Selected body speed history"><path d="M0 35H200" stroke="#7185a520"/>{data.length>1&&<polyline points={points} fill="none" stroke="#96accf" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/>}</svg>;}
