'use client';
import { useLanguage, useT } from '@/lib/i18n/language';
import { useEffect, useRef, useState } from 'react';
import { FolderOpen, Undo2, Activity, ArrowUpRight, ChevronRight, CircleHelp, Crosshair, Focus, Globe2, Layers3, Minus, MousePointer2, Orbit, Pause, Play, Plus, Rocket, RotateCcw, SkipForward, SlidersHorizontal, Sparkles, Sun, Target, Trash2, X } from 'lucide-react';
import HubNavigation, { SimulatorId } from '@/components/hub-navigation';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarTrigger } from '@/components/ui/sidebar';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { Slider } from '@/components/ui/slider';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import SolarCanvas, { SolarControls } from './solar-canvas';
import { AU_KM, Body, G, KM_S, MAX_DAY, MIN_DAY, MOONS, PLANETS, Scenario, SolarEngine, dateDay, dayDate, length, sub } from '@/lib/solar/engine';
import './solar.css';
import SolarSaves, { useSolarAutosave } from './solar-saves';
import { registerSolarTools } from '@/lib/solar/webmcp';
const scenarios:{id:Scenario;title:string;description:string;number:string}[]=[
 {id:'earth-speed',title:'A faster Earth',description:'Increase Earth’s speed by 35% and watch its orbit change.',number:'01'},
 {id:'jupiter-comet',title:'An encounter with Jupiter',description:'Send a comet near the gas giant and follow its deflection.',number:'02'},
 {id:'binary',title:'Two suns, one planet',description:'Explore a planet orbiting a pair of stars.',number:'03'},
 {id:'mars-launch',title:'The road to Mars',description:'Explore a transfer attempt. Timing matters as much as speed.',number:'04'},
];
export default function SolarLab({active,onNavigate}:{active:boolean;onNavigate:(id:SimulatorId)=>void}){
 const tr = useT();
 const { language } = useLanguage();
 const [engine]=useState(()=>new SolarEngine());const [,refresh]=useState(0);const controls=useRef<SolarControls|null>(null);
 const [selected,setSelected]=useState<string|null>('earth');const [follow,setFollow]=useState<string|null>(null);const [view,setView]=useState<'3d'|'top'>('3d');const [tool,setTool]=useState<'select'|'probe'|'comet'>('select');const [orbits,setOrbits]=useState(true);const [labels,setLabels]=useState(true);const [vectors,setVectors]=useState(false);const [gravity,setGravity]=useState(false);const [trueScale,setTrueScale]=useState(false);const [moons,setMoons]=useState(true);const [help,setHelp]=useState(false);const [experiments,setExperiments]=useState(false);const [fps,setFps]=useState(0);const [error,setError]=useState('');const [confirm,setConfirm]=useState<'reference'|'reset'|Scenario|null>(null);const [date,setDate]=useState(dayDate(engine.day));const [massFactor,setMassFactor]=useState(1);const [velocityFactor,setVelocityFactor]=useState(1.2);const [positionX,setPositionX]=useState(engine.bodies.find(b=>b.id==='earth')!.p[0].toFixed(4));const [positionY,setPositionY]=useState(engine.bodies.find(b=>b.id==='earth')!.p[1].toFixed(4));
 useEffect(()=>active?registerSolarTools(engine,()=>refresh(n=>n+1)):undefined,[active,engine]);
 const sync=()=>{refresh(n=>n+1);};const body=engine.bodies.find(b=>b.id===selected);const sun=engine.bodies.find(b=>b.id==='sun');const parent=engine.bodies.find(b=>b.id===(body?.parent??'sun'));const distance=body&&sun?length(sub(body.p,sun.p)):null;const speed=body?length(body.v)*KM_S:0;
 const select=(id:string,focus=false)=>{setTool('select');setSelected(id);engine.selected=id;engine.history=[];setMassFactor(1);setVelocityFactor(1.2);const b=engine.bodies.find(b=>b.id===id);if(b){setPositionX(b.p[0].toFixed(4));setPositionY(b.p[1].toFixed(4));}if(focus){setFollow(id);controls.current?.focus(id);}sync();};
 const attempt=(fn:()=>void)=>{try{fn();setError('');sync();}catch(e){setError((e as Error).message);}};
 const prepareTool=(value:'select'|'probe'|'comet')=>{setTool(value);if(value!=='select'){engine.experiment();engine.paused=true;setFollow(null);setView('top');setError('');sync();}};
 const reset=(action:'reference'|'reset'|Scenario)=>{attempt(()=>{if(action==='reference'||action==='reset'){engine.reset(Math.max(MIN_DAY,Math.min(MAX_DAY-1,engine.day)));setDate(dayDate(engine.day));setSelected('earth');}else{engine.scenario(action);setSelected(engine.selected);}setFollow(null);setTool('select');setView('3d');controls.current?.fit(action==='binary');if(action==='binary')controls.current?.zoom(1.8);if(action==='jupiter-comet'){const j=engine.bodies.find(b=>b.id==='jupiter');if(j){setFollow(j.id);controls.current?.focus(j.id);controls.current?.zoom(.025);}}setExperiments(false);});};
 const requestReset=(action:'reference'|'reset'|Scenario)=>{if(engine.mode==='experiment')setConfirm(action);else reset(action);};
 useEffect(()=>{if(!active)return;const key=(e:KeyboardEvent)=>{const t=e.target as HTMLElement;if(t.closest('input,textarea,button,[role="dialog"],[role="alertdialog"],[role="slider"],[role="combobox"],[role="tab"],[contenteditable="true"]'))return;if(e.code==='Space'){e.preventDefault();engine.paused=!engine.paused;refresh(n=>n+1);}if(e.key==='Escape'){setTool('select');setSelected(null);setFollow(null);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[engine,active]);
 const [ghosts,setGhosts]=useState(true);const [saves,setSaves]=useState(false);
 const restored=(fit=true)=>{if(fit)controls.current?.fit(true);setSelected(engine.bodies.some(b=>b.id===engine.selected)?engine.selected:null);setFollow(null);setTool('select');setDate(dayDate(engine.day));sync();};
 const autosave=useSolarAutosave(engine,active,restored,setError);
 const rewind=(index:number)=>{engine.rewind(index);restored(false);};
 const separation=body?engine.separation(body.id):null;
 const baseMass=body?.id==='sun'?1:PLANETS.find(p=>p.id===body?.id)?.mass??MOONS.find(p=>p.id===body?.id)?.mass??body?.mass??1;
 return <SidebarProvider style={{'--sidebar-width':'264px'} as React.CSSProperties} className="app-shell solar-shell"><Sidebar className="observatory-sidebar" inert={!autosave.ready}><SidebarHeader className="brand"><div className="brand-symbol"><Orbit size={23}/></div><div><strong>{tr("simulation")}<span>{tr("hub")}</span></strong><small>{tr("A SPACE FOR CURIOSITY")}</small></div><SidebarTrigger className="mobile-sidebar-close" aria-label={tr("Close settings")}/></SidebarHeader><SidebarContent><HubNavigation current="solar" onNavigate={onNavigate}/><div className="sidebar-divider"/>
 <div className="sidebar-section solar-mode"><div className="section-title"><SlidersHorizontal size={15}/><span>{tr("Laboratory mode")}</span></div><Tabs value={engine.mode} onValueChange={v=>v==='experiment'?attempt(()=>engine.experiment()):requestReset('reference')}><TabsList className="view-tabs solar-mode-tabs"><TabsTrigger value="explore">{tr("Explore")}</TabsTrigger><TabsTrigger value="experiment">{tr("Experiment")}</TabsTrigger></TabsList></Tabs><p className="solar-sidebar-note">{tr(engine.mode==='explore'?'Follow the planets using approximate reference orbits.':'Change the system and let gravity take over.')}</p></div><div className="sidebar-divider"/>
 <div className="sidebar-section solar-objects"><div className="section-title"><Globe2 size={15}/><span>{tr("Objects")}</span><span className="solar-count">{tr(engine.bodies.length)}</span></div><div className="solar-object-list">{engine.bodies.filter(b=>b.kind!=='moon').map(b=><button key={b.id} className={selected===b.id?'selected':''} onClick={()=>select(b.id,true)} aria-label={tr(`Inspect ${b.name}`)} aria-pressed={selected===b.id}><span className={`body-dot ${b.kind}`} style={{'--body-color':b.color} as React.CSSProperties}/><span>{tr(b.name)}</span>{b.kind==='star'?<Sun size={12}/>:<ChevronRight size={12}/>}</button>)}</div>{moons&&<details className="solar-moon-list"><summary>{tr("Major moons ")}<span>{tr(engine.bodies.filter(b=>b.kind==='moon').length)}</span></summary>{engine.bodies.filter(b=>b.kind==='moon').map(b=><button key={b.id} onClick={()=>select(b.id,true)} aria-label={tr(`Inspect ${b.name}`)}><span className="body-dot" style={{'--body-color':b.color} as React.CSSProperties}/>{tr(b.name)}<small>{tr(engine.bodies.find(p=>p.id===b.parent)?.name??'Independent')}</small></button>)}</details>}</div><div className="sidebar-divider"/>
 <div className="sidebar-section"><div className="section-title"><Layers3 size={15}/><span>{tr("View layers")}</span></div><Layer label={tr("Ghost comparison")} value={ghosts} onChange={setGhosts}/>{engine.mode==='experiment'&&<button className="solar-baseline-button" onClick={()=>attempt(()=>engine.setBaseline())}>{tr("Use current state as baseline")}</button>}<Layer label={tr("Orbits & trails")} value={orbits} onChange={setOrbits}/><Layer label={tr("Object labels")} value={labels} onChange={setLabels}/><Layer label={tr("Major moons")} value={moons} onChange={setMoons}/><Layer label={tr("Velocity arrows")} value={vectors} onChange={setVectors}/><Layer label={tr("Gravity direction")} value={gravity} onChange={setGravity}/><Layer label={tr("True planet sizes")} value={trueScale} onChange={setTrueScale}/></div><div className="sidebar-divider"/>
 <div className="sidebar-section solar-date"><label htmlFor="reference-date">{tr("Reference date")}</label><input id="reference-date" type="date" value={date} min="1800-01-01" max="2049-12-31" disabled={engine.mode==='experiment'} onChange={e=>setDate(e.target.value)}/><button className="button secondary" disabled={engine.mode==='experiment'} onClick={()=>attempt(()=>{engine.reset(dateDay(date));engine.paused=true;setFollow(null);setSelected('earth');})}>{tr("Go to date")}</button></div>
 </SidebarContent><SidebarFooter className="sidebar-bottom"><button onClick={()=>setHelp(true)}><CircleHelp size={17}/>{tr("Lab notes")}<span>↗</span></button><div className="version-line"><span>{tr("SOLAR SYSTEM LAB")}</span><span>02</span></div></SidebarFooter></Sidebar>
 <main className="workspace solar-workspace" inert={!autosave.ready}><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>{tr("Simulations")}</span><ChevronRight size={14}/><strong>{tr("Solar System Lab")}</strong></div><div className="solar-header-actions"><button className="button secondary" aria-label={tr("Saved solar experiments")} disabled={!autosave.ready} onClick={()=>{engine.paused=true;sync();setSaves(true);}}><FolderOpen size={15}/><span>{tr("Saved experiments")}</span></button><button className="button secondary solar-experiments-button" aria-label={tr("Experiments")} onClick={()=>setExperiments(true)}><Sparkles size={15}/><span>{tr("Experiments")}</span></button></div></header><div className="page-heading"><div><div className="title-row"><h1>{tr("A little closer ")}<span>{tr("to the cosmos.")}</span></h1><span className="species-tag solar-mode-tag">{tr(engine.mode==='explore'?'REFERENCE ORBITS':'GRAVITY SANDBOX')}</span></div><p>{tr("Explore our neighborhood. Discover what keeps it in motion.")}</p></div><button className="icon-button" aria-label={tr("About Solar System Lab")} onClick={()=>setHelp(true)}><CircleHelp size={19}/></button></div>
 {error&&<div className="error-banner" role="alert">{tr(error)}<button className="icon-button" aria-label={tr("Dismiss error")} onClick={()=>setError('')}><X size={14}/></button></div>}
 <section className="simulation-panel solar-panel" aria-label={tr("Solar System Lab")}><div className="world-topbar solar-topbar"><Tabs value={view} onValueChange={v=>{setView(v as '3d'|'top');setTool('select');}}><TabsList className="view-tabs"><TabsTrigger value="3d"><Orbit size={15}/>{tr("3D view")}</TabsTrigger><TabsTrigger value="top"><Layers3 size={15}/>{tr("Orbital map")}</TabsTrigger></TabsList></Tabs><div className="playback"><span className="solar-date-display">{tr(dayDate(engine.day))}</span><button className="icon-button pause-button" aria-label={tr(engine.paused?'Play Solar System':'Pause Solar System')} onClick={()=>{engine.paused=!engine.paused;sync();}}>{engine.paused?<Play size={15}/>:<Pause size={15}/>}</button><button className="icon-button" aria-label={tr("Advance one day")} title={tr("Advance one day; close encounters may advance less")} onClick={()=>{engine.paused=false;engine.tick(1,1500);engine.paused=true;sync();}}><SkipForward size={15}/></button><Select value={String(engine.speed)} onValueChange={v=>{engine.speed=Number(v);sync();}}><SelectTrigger aria-label={tr("Solar simulation speed")} className="speed-select"><SelectValue/></SelectTrigger><SelectContent>{[.1,1,5,10,30,100,365].map(v=><SelectItem key={v} value={String(v)}>{tr(v)}{tr(" d / s")}</SelectItem>)}</SelectContent></Select><button className="icon-button" aria-label={tr("Reset Solar System")} onClick={()=>requestReset('reset')}><RotateCcw size={15}/></button></div></div>
 <div className="world-area solar-world"><SolarCanvas engine={engine} active={active&&autosave.ready} display={{ghosts,language,orbits,labels,vectors,gravity,trueScale,moons,follow,selected}} view={view} tool={tool} controls={controls} onSelect={select} onPan={()=>setFollow(null)} onError={setError} onChange={f=>{setFps(f);if(selected&&!engine.bodies.some(b=>b.id===selected)){setSelected(engine.bodies.some(b=>b.id===engine.selected)?engine.selected:null);setFollow(null);}refresh(n=>n+1);}}/>
 {engine.mode==='experiment'&&ghosts&&<div className="solar-ghost-legend"><i/>{tr("Ghost: unchanged baseline")}</div>}<div className="solar-observation"><span className={engine.paused?'':'solar-live'}/>{tr(engine.paused?'TIME PAUSED':'IN MOTION')}<span className="solar-observation-divider"/>{tr(engine.mode==='explore'?'OUR SOLAR SYSTEM':'EXPERIMENTAL SYSTEM')}</div><div className="solar-framing"><button onClick={()=>controls.current?.fit(false)}>{tr("Inner system")}</button><button onClick={()=>controls.current?.fit(true)}>{tr("Full system")}</button></div>
 <div className="world-tools solar-tools" role="toolbar" aria-label={tr("Space tools")}><button aria-label={tr("Select a body")} aria-pressed={tool==='select'} className={tool==='select'?'active':''} onClick={()=>prepareTool('select')} title={tr("Select")}><MousePointer2 size={18}/></button><button aria-label={tr("Launch a probe")} aria-pressed={tool==='probe'} className={tool==='probe'?'active':''} onClick={()=>prepareTool('probe')} title={tr("Launch a probe")}><Rocket size={18}/></button><button aria-label={tr("Launch a comet")} aria-pressed={tool==='comet'} className={tool==='comet'?'active':''} onClick={()=>prepareTool('comet')} title={tr("Launch a comet")}><Sparkles size={18}/></button></div>
 {body&&<aside className="solar-inspector" aria-label={tr(`${body.name} inspector`)}><div className="solar-inspector-header"><span className="solar-kicker">{tr(body.kind==='moon'?`MOON OF ${parent?.name.toUpperCase()??'REMOVED BODY'}`:body.kind.toUpperCase())}</span><button className="icon-button" aria-label={tr("Close body inspector")} onClick={()=>setSelected(null)}><X size={15}/></button></div><div className="solar-body-title"><span className="inspector-planet" style={{'--body-color':body.color} as React.CSSProperties}/><h2>{tr(body.name)}</h2></div><p className="solar-body-description">{tr(PLANETS.find(p=>p.id===body.id)?.description??(body.kind==='star'?'The gravitational heart of this system.':body.kind==='moon'?'A close companion. Zoom in to explore its orbit.':'A custom object following the gravity of this system.'))}</p><dl className="solar-values"><div><dt>{tr("Speed")}</dt><dd>{tr(speed.toFixed(2))} <span>{tr("km/s")}</span></dd></div><div><dt>{tr(body.kind==='moon'?'From parent':'From Sun')}</dt><dd>{tr(body.kind==='moon'&&parent?`${Math.round(length(sub(body.p,parent.p))*AU_KM).toLocaleString()} km`:distance!==null?`${distance.toFixed(3)} AU`:'—')}</dd></div><div><dt>{tr("Mass")}</dt><dd>{tr(body.kind==='star'?`${body.mass.toFixed(3)} M☉`:`${(body.mass/3.0035e-6).toLocaleString(undefined,{maximumSignificantDigits:4})} M⊕`)}</dd></div><div><dt>{tr("Radius")}</dt><dd>{tr(body.radius<1?(body.radius*1000).toLocaleString(undefined,{maximumFractionDigits:1}):body.radius.toLocaleString(undefined,{maximumFractionDigits:1}))} <span>{tr(body.radius<1?'m':'km')}</span></dd></div>{engine.mode==='experiment'&&ghosts&&<div className="solar-delta"><dt>{tr("From baseline")}</dt><dd>{separation===null?tr("No matching body"):<>{tr(separation<1?separation.toFixed(3):Math.round(separation).toLocaleString())} <span>{tr("km")}</span></>}</dd></div>}</dl><button className={`button solar-follow ${follow===body.id?'following':'secondary'}`} onClick={()=>{if(follow===body.id)setFollow(null);else{setFollow(body.id);controls.current?.focus(body.id);}}}><Target size={14}/>{tr(follow===body.id?'Following · stop':'Follow & focus')}<ArrowUpRight size={13}/></button>
 {engine.mode==='experiment'?<details className="solar-body-edit" onToggle={e=>{if(e.currentTarget.open){setPositionX(body.p[0].toFixed(5));setPositionY(body.p[1].toFixed(5));}}}><summary><SlidersHorizontal size={14}/>{tr("Edit this body")}</summary><label>{tr("Mass multiplier ")}<output>{tr(massFactor.toFixed(1))}×</output></label><Slider aria-label={tr("Body mass multiplier")} value={[massFactor]} min={.1} max={10} step={.1} onValueChange={v=>setMassFactor(v[0])}/><button className="button secondary" onClick={()=>attempt(()=>engine.setMass(body.id,baseMass*massFactor))}>{tr("Apply mass")}</button><label>{tr("Current speed × ")}<output>{tr(velocityFactor.toFixed(2))}</output></label><Slider aria-label={tr("Body velocity multiplier")} value={[velocityFactor]} min={0} max={2} step={.05} onValueChange={v=>setVelocityFactor(v[0])}/><button className="button secondary" onClick={()=>attempt(()=>engine.velocity(body.id,velocityFactor))}>{tr("Apply velocity")}</button><div className="solar-position"><label>{tr("X · AU")}<input aria-label={tr("Body X position in AU")} type="number" step=".01" min="-100" max="100" value={positionX} onChange={e=>setPositionX(e.target.value)}/></label><label>{tr("Y · AU")}<input aria-label={tr("Body Y position in AU")} type="number" step=".01" min="-100" max="100" value={positionY} onChange={e=>setPositionY(e.target.value)}/></label></div><button className="button secondary" onClick={()=>attempt(()=>{if(!positionX.trim()||!positionY.trim())throw new Error('Enter both coordinates.');engine.move(body.id,[Number(positionX),Number(positionY),body.p[2]]);})}>{tr("Move body")}</button><button className="button solar-remove" onClick={()=>attempt(()=>{engine.remove(body.id);setSelected(null);setFollow(null);})}><Trash2 size={13}/>{tr("Remove ")}{tr(body.name)}</button></details>:<button className="solar-edit-link" onClick={()=>attempt(()=>engine.experiment())}>{tr("Experiment with this body ")}<ArrowUpRight size={13}/></button>}
 </aside>}
 <div className="world-hint solar-hint">{tool==='select'?<><MousePointer2 size={13}/>{tr(follow?`Following ${engine.bodies.find(b=>b.id===follow)?.name??'object'} · drag to release`:'Drag to explore · Shift-drag to rotate')}</>:<>{tr("Drag to launch a ")}{tr(tool)}{tr(" · arrow sets velocity · preview is approximate")}</>}</div><div className="zoom-controls solar-zoom"><button aria-label={tr("Zoom in on Solar System")} onClick={()=>controls.current?.zoom(1.6)}><Plus size={17}/></button><button aria-label={tr("Zoom out of Solar System")} onClick={()=>controls.current?.zoom(1/1.6)}><Minus size={17}/></button><span/><button aria-label={tr("Fit Solar System")} onClick={()=>controls.current?.fit(true)}><Focus size={17}/></button></div><span className="solar-scale-note">{tr(trueScale?'TRUE PLANET SIZES · distances to scale':'PLANETS ENLARGED · distances to scale')}</span>
 </div>{engine.mode==='experiment'&&<div className="solar-timeline"><div className="solar-timeline-title"><span>{tr('Rewind experiment')}</span><span>{tr(engine.cursor<engine.timeline.length-1?'Play or edit here to start a new branch':'Live recording · last 240 checkpoints')}</span></div><div className="solar-timeline-controls"><button className="icon-button" aria-label={tr('Undo last edit')} title={tr('Undo last edit')} disabled={engine.undoIndex<0} onClick={()=>rewind(engine.undoIndex)}><Undo2 size={16}/></button><button className="icon-button" aria-label={tr('Previous checkpoint')} disabled={engine.cursor<=0} onClick={()=>rewind(engine.cursor-1)}><ChevronRight size={15} style={{transform:'rotate(180deg)'}}/></button><input aria-label={tr('Experiment timeline')} type="range" min={0} max={Math.max(0,engine.timeline.length-1)} value={Math.max(0,engine.cursor)} disabled={engine.timeline.length<2} onChange={e=>rewind(Number(e.target.value))}/><button className="icon-button" aria-label={tr('Next checkpoint')} disabled={engine.cursor>=engine.timeline.length-1} onClick={()=>rewind(engine.cursor+1)}><ChevronRight size={15}/></button><output>{tr(engine.timeline.length?((engine.day-engine.timeline[0].day).toFixed(1)):'0.0')} {tr('days recorded')}</output></div></div>}<div className="solar-metrics"><div><span className="solar-kicker">{tr("SYSTEM")}</span><strong>{tr(engine.bodies.length)}<small>{tr("objects")}</small></strong><p>{tr(engine.mode==='explore'?'Sun, planets & selected moons':'Newtonian gravity · physical collisions')}</p></div><div><span className="solar-kicker">{tr(body?`${body.name.toUpperCase()} SPEED`:'SELECT A BODY')}</span><strong>{tr(body?speed.toFixed(2):'—')}<small>{tr("km/s")}</small></strong><p>{tr(engine.mode==='explore'?'Approximate JPL reference model':'Speed in the simulation frame')}</p></div><div className="solar-chart"><span className="solar-kicker">{tr("SPEED OVER TIME")}</span><Sparkline data={engine.history.map(h=>h.speed)}/><p>{tr(engine.history.length>1?`${(engine.history.at(-1)!.day-engine.history[0].day).toFixed(1)} simulated days`:'Collecting observations…')}</p></div></div></section>
 <footer className="workspace-footer solar-footer"><span>{tr(engine.events[0]??(engine.mode==='explore'?'JPL orbital elements · approximate positions':'Edits apply to this sandbox session'))}{engine.events[0]&&<button aria-label={tr("Dismiss event")} onClick={()=>{engine.events.shift();sync();}}><X size={12}/></button>}</span><span className="solar-autosave-status" role="status">{tr(autosave.status)}</span><span>{tr(fps)}{tr(" FPS ")}<i>·</i>{tr("Space to pause")}</span></footer></main>
 <SolarSaves engine={engine} open={saves} onOpenChange={setSaves} onRestore={restored} onError={setError} onSaved={()=>void autosave.write()}/>
 <Dialog open={experiments} onOpenChange={setExperiments}><DialogContent className="solar-dialog"><DialogHeader><DialogTitle>{tr("A change worth watching.")}</DialogTitle><DialogDescription>{tr("Choose an experiment. Each starts paused with its own setup.")}</DialogDescription></DialogHeader><div className="solar-scenario-list">{scenarios.map(s=><button key={s.id} onClick={()=>requestReset(s.id)}><span>{tr(s.number)}</span><div><h3>{tr(s.title)}</h3><p>{tr(s.description)}</p></div><ArrowUpRight size={19}/></button>)}</div></DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="solar-dialog solar-notes"><DialogHeader><DialogTitle>{tr("Inside Solar System Lab")}</DialogTitle><DialogDescription>{tr("Two ways to explore the same neighborhood.")}</DialogDescription></DialogHeader><h3>{tr("Explore the reference system")}</h3><p>{tr("Planets follow JPL’s approximate Keplerian elements for 1800–2050. These are calculated positions, not a live Horizons feed. Earth uses the Earth–Moon barycenter approximation. Selected moons use illustrative circular orbits with approximate periods and phases.")}</p><h3>{tr("Experiment with gravity")}</h3><p>{tr("The sandbox begins from those positions and velocities. Bodies then interact through Newtonian gravity. Collisions merge bodies at their physical radii; enlarged display sizes do not affect physics. Relativity, tides, atmospheric drag, and fragmentation are omitted.")}</p><p>{tr("Fast playback may run slower during close encounters to maintain smaller calculation steps. A launch preview treats other bodies as stationary, so it is a rough guide. Drag length sets launch speed: one AU equals about 34.6 km/s.")}</p><h3>{tr("Find your way around")}</h3><p>{tr("Drag to pan, Shift-drag or right-drag to rotate, and scroll or pinch to zoom. Use the object list to focus on distant planets and moons. Arrow keys pan the focused canvas, +/− zoom, Enter selects the next body, and Space pauses time.")}</p><p>{tr("The 3D view uses textured spheres with approximate axial tilt and rotation. Surface maps and rotational phase are illustrative, not live imagery. Distances stay to scale; planets are enlarged unless true sizes are enabled. The gravity arrow shows direction only.")}</p><p>{tr("Solar experiments autosave locally every 30 seconds and when leaving the lab. Rewind restores recorded states; playing or editing from the past replaces the later branch. The last 240 checkpoints are retained. Ghosts show an unchanged gravity simulation from the comparison baseline. Named saves and exported files include the baseline and rewind history.")}</p><div className="solar-sources"><a href="https://www.solarsystemscope.com/textures/" target="_blank" rel="noreferrer">{tr("Planet maps: Solar System Scope ↗")}</a><a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">{tr("Texture license: CC BY 4.0 ↗")}</a><a href="https://ssd.jpl.nasa.gov/planets/approx_pos.html" target="_blank" rel="noreferrer">{tr("JPL orbital elements ↗")}</a><a href="https://ssd.jpl.nasa.gov/astro_par.html" target="_blank" rel="noreferrer">{tr("JPL physical constants ↗")}</a></div></DialogContent></Dialog>
 <AlertDialog open={confirm!==null} onOpenChange={open=>{if(!open)setConfirm(null);}}><AlertDialogContent className="solar-dialog"><AlertDialogHeader><AlertDialogTitle>{tr("Replace this experiment?")}</AlertDialogTitle><AlertDialogDescription>{tr("Your current solar edits and added objects will be replaced. The ant colony is kept.")}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{tr("Keep experiment")}</AlertDialogCancel><AlertDialogAction onClick={()=>{if(confirm)reset(confirm);setConfirm(null);}}>{tr("Replace system")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>;
}
function Layer({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){
 const tr = useT();return <label className="layer-toggle solar-layer"><span>{tr(label)}</span><Switch aria-label={tr(label)} checked={value} onCheckedChange={onChange}/></label>;}
function Sparkline({data}:{data:number[]}){
 const tr = useT();const min=Math.min(...data),max=Math.max(...data),range=max-min||Math.max(max*.02,1);const points=data.map((v,i)=>`${i/Math.max(1,data.length-1)*200},${35-(v-min)/range*30}`).join(' ');return <svg viewBox="0 0 200 40" role="img" aria-label={tr("Selected body speed history")}><path d="M0 35H200" stroke="#7185a520"/>{data.length>1&&<polyline points={points} fill="none" stroke="#96accf" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/>}</svg>;}
