'use client';
import { useEffect, useRef } from 'react';
import { Body, G, SolarEngine, Vec, add, length, scale, sub } from '@/lib/solar/engine';
import { Camera, Display, Hit, drawSolar, unproject } from '@/lib/solar/renderer';
export interface SolarControls { zoom:(factor:number)=>void; fit:(outer?:boolean)=>void; focus:(id:string)=>void; }
export default function SolarCanvas({engine,active,display,view,tool,controls,onSelect,onChange,onPan,onError}:{engine:SolarEngine;active:boolean;display:Display;view:'3d'|'top';tool:'select'|'probe'|'comet';controls:React.RefObject<SolarControls|null>;onSelect:(id:string)=>void;onChange:(fps:number)=>void;onPan:()=>void;onError:(s:string)=>void}){
 const ref=useRef<HTMLCanvasElement>(null);const latest=useRef({display,tool,onSelect,onChange,onPan,onError});latest.current={display,tool,onSelect,onChange,onPan,onError};
 const camera=useRef<Camera>({center:[0,0,0],range:2.35,yaw:-.3,tilt:.85});
 useEffect(()=>{camera.current.tilt=view==='top'?0:.85;},[view]);
 useEffect(()=>{const canvas=ref.current;if(!canvas||!active)return;const ctx=canvas.getContext('2d');if(!ctx)return;let w=0,h=0,hits:Hit[]=[],raf=0,last=performance.now(),lastUI=last,frames=0;let drag:{x:number;y:number;lastX:number;lastY:number;moved:boolean;shift:boolean;launch:boolean;start:Vec}|null=null;let launching:{start:Vec;end:Vec;preview:Vec[]}|undefined;const pointers=new Map<number,{x:number;y:number}>();let pinch=0;
 const zoom=(factor:number)=>{camera.current.range=Math.max(.0001,Math.min(150,camera.current.range/factor));};
 controls.current={zoom,fit:(outer=false)=>{camera.current.center=[0,0,0];camera.current.range=outer?37:2.35;latest.current.onPan();},focus:id=>{const b=engine.bodies.find(b=>b.id===id);if(!b)return;camera.current.center=[...b.p];camera.current.range=b.kind==='moon'?.006:b.id==='jupiter'?.022:b.id==='saturn'?.032:b.id==='earth'?.007:b.kind==='star'?.09:.001+6*b.radius/149597870.7;}};
 const observer=new ResizeObserver(()=>{const rect=canvas.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=Math.min(devicePixelRatio,2);canvas.width=Math.max(1,w*dpr);canvas.height=Math.max(1,h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);});observer.observe(canvas);
 const frame=(now:number)=>{if(w&&h&&!document.hidden){const dt=Math.min(.05,(now-last)/1000);engine.tick(dt*engine.speed);hits=drawSolar(ctx,w,h,engine,camera.current,latest.current.display,launching).hits;frames++;if(now-lastUI>180){latest.current.onChange(Math.round(frames*1000/(now-lastUI)));lastUI=now;frames=0;}}last=now;raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);
 const point=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};};
 const down=(e:PointerEvent)=>{if(e.button!==0&&e.button!==2)return;canvas.focus();const p=point(e);pointers.set(e.pointerId,p);canvas.setPointerCapture(e.pointerId);if(pointers.size===2){const [a,b]=[...pointers.values()];pinch=Math.hypot(a.x-b.x,a.y-b.y);drag=null;launching=undefined;return;}drag={x:p.x,y:p.y,lastX:p.x,lastY:p.y,moved:false,shift:e.shiftKey||e.button===2,launch:latest.current.tool!=='select',start:unproject(p.x,p.y,camera.current,w,h)};};
 const move=(e:PointerEvent)=>{const p=point(e);if(pointers.has(e.pointerId))pointers.set(e.pointerId,p);if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch)zoom(d/pinch);pinch=d;return;}if(!drag)return;const dx=p.x-drag.lastX,dy=p.y-drag.lastY;drag.moved ||= Math.hypot(p.x-drag.x,p.y-drag.y)>4;
 if(drag.launch){const end=unproject(p.x,p.y,camera.current,w,h),v=scale(sub(end,drag.start),.02);const temp:Body[]=engine.bodies.map(b=>({...b,p:[...b.p] as Vec,v:[...b.v] as Vec,trail:[]}));const body:Body={id:'preview',name:'Preview',kind:'probe',color:'#fff',mass:0,radius:.001,p:[...drag.start],v,trail:[]};temp.push(body);const preview:Vec[]=[[...body.p]];const dt=Math.max(.002,Math.min(2,camera.current.range));for(let i=0;i<70;i++){// A test-particle prediction with frozen source positions; illustrative only.
 let a:Vec=[0,0,0];for(const b of temp){if(b===body)continue;const d=sub(b.p,body.p);a=add(a,scale(d,G*b.mass/Math.max(length(d)**3,1e-14)));}body.v=add(body.v,scale(a,dt));body.p=add(body.p,scale(body.v,dt));preview.push([...body.p]);}launching={start:drag.start,end,preview};
 }else if(drag.shift){camera.current.yaw+=dx*.006;camera.current.tilt=Math.max(0,Math.min(1.4,camera.current.tilt+dy*.005));}else if(drag.moved){latest.current.onPan();const before=unproject(drag.lastX,drag.lastY,camera.current,w,h),after=unproject(p.x,p.y,camera.current,w,h);camera.current.center=add(camera.current.center,sub(before,after));}
 drag.lastX=p.x;drag.lastY=p.y;};
 const up=(e:PointerEvent)=>{pointers.delete(e.pointerId);pinch=0;if(drag){if(drag.launch&&launching&&drag.moved){try{const id=engine.launch(launching.start,scale(sub(launching.end,launching.start),.02),latest.current.tool==='comet'?'comet':'probe');latest.current.onSelect(id);latest.current.onChange(60);}catch(err){latest.current.onError((err as Error).message);}}else if(!drag.moved){const p=point(e),hit=hits.filter(a=>Math.hypot(a.x-p.x,a.y-p.y)<a.r+7).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(hit)latest.current.onSelect(hit.id);}}drag=null;launching=undefined;};
 const cancel=(e:PointerEvent)=>{pointers.delete(e.pointerId);drag=null;launching=undefined;pinch=0;};
 const wheel=(e:WheelEvent)=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.0015));};const context=(e:Event)=>e.preventDefault();
 const key=(e:KeyboardEvent)=>{if(e.key==='+'||e.key==='='){zoom(1.3);e.preventDefault();}if(e.key==='-'){zoom(1/1.3);e.preventDefault();}const axis=e.key==='ArrowLeft'?[-1,0]:e.key==='ArrowRight'?[1,0]:e.key==='ArrowUp'?[0,1]:e.key==='ArrowDown'?[0,-1]:null;if(axis){latest.current.onPan();camera.current.center[0]+=axis[0]*camera.current.range*.1;camera.current.center[1]+=axis[1]*camera.current.range*.1;e.preventDefault();}if(e.key==='Enter'){const idx=engine.bodies.findIndex(b=>b.id===latest.current.display.selected),b=engine.bodies[(idx+1)%engine.bodies.length];if(b)latest.current.onSelect(b.id);e.preventDefault();}};
 canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('wheel',wheel,{passive:false});canvas.addEventListener('contextmenu',context);canvas.addEventListener('keydown',key);
 return()=>{cancelAnimationFrame(raf);observer.disconnect();controls.current=null;canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);canvas.removeEventListener('wheel',wheel);canvas.removeEventListener('contextmenu',context);canvas.removeEventListener('keydown',key);};
 },[active,engine,controls]);
 return <canvas ref={ref} className={`solar-canvas ${tool!=='select'?'launch-cursor':''}`} role="img" aria-label="Interactive Solar System. Drag to pan, Shift-drag to rotate, scroll to zoom. Enter selects the next body. Use the Objects list to inspect any planet." tabIndex={0}/>;
}
