import assert from 'node:assert/strict';
import {AntSimulation,createColony,FIXED_DT} from '../lib/simulation/engine';
import {validateSave} from '../lib/simulation/validation';
import {isOpen,NestRoutes,distance,cellIndex,neighbors,cellPoint} from '../lib/simulation/spatial';
import {deposit,decayFields} from '../lib/simulation/pheromones';
import {WORLD,NEST_CENTER,NEST_LAYER_SIZE} from '../lib/simulation/types';
import {NEST_CELLS,NEST_SLICE,NURSERY,projectNest,volumeIndex} from '../lib/simulation/nest-volume';
import {SpatialIndex} from '../lib/simulation/spatial';
let passed=0;function test(name:string,fn:()=>void){try{fn();passed++;console.log(`PASS ${name}`);}catch(e){console.error(`FAIL ${name}`);throw e;}}
function runSeconds(sim:AntSimulation,seconds:number){sim.step(Math.round(seconds/FIXED_DT));}
test('initial colony has 200 workers, queen, brood, and valid geometry',()=>{const s=createColony();assert.equal(s.ants.length,201);assert.equal(s.brood.length,36);assert.equal(s.ants.filter(a=>a.task==='queen').length,1);validateSave(s);const bad=s.ants.filter(a=>!isOpen(s,a,a.view));assert.equal(bad.length,0,`Ants in walls/rocks: ${bad.map(a=>a.id)}`);});
test('seeded runs and save/resume produce identical state',()=>{const a=new AntSimulation(123),b=new AntSimulation(123);runSeconds(a,12.1);runSeconds(b,12.1);assert.deepEqual(a.state,b.state);const c=new AntSimulation();c.command({type:'load',state:JSON.parse(a.serialize())});c.paused=false;runSeconds(a,20);runSeconds(c,20);assert.deepEqual(a.state,c.state);});
test('pause freezes all state',()=>{const a=new AntSimulation();a.command({type:'pause',paused:true});const before=a.serialize();a.step(300);assert.equal(a.serialize(),before);});
test('invalid imports and invalid commands preserve the running colony',()=>{const a=new AntSimulation();runSeconds(a,2);const before=a.serialize();for(const value of [{},{...a.state,version:99},{...a.state,ants:[{...a.state.ants[0],energy:NaN}]}])assert.throws(()=>a.command({type:'load',state:value}));assert.throws(()=>a.command({type:'settings',settings:{temperature:500}}));assert.throws(()=>a.command({type:'speed',speed:100}));assert.equal(a.serialize(),before);});
test('pheromone reinforcement and decay',()=>{const a=new AntSimulation();deposit(a.state,{x:100,y:100},10);const sum=a.state.pheromones.reduce((x,y)=>x+y,0);decayFields(a.state,60);assert.ok(a.state.pheromones.reduce((x,y)=>x+y,0)<sum*.5);});
test('a locally encountered resource is collected and delivered',()=>{const a=new AntSimulation(99,1),worker=a.state.ants[1];worker.view='surface';worker.x=720;worker.y=430;worker.age=30;worker.energy=1;a.state.resources=[{id:a.state.nextId++,x:725,y:430,kind:'carbohydrate',amount:100,initial:100,radius:20}];a.context.rebuild(a.state);const start=a.state.stores.carbohydrate;runSeconds(a,1);assert.equal(worker.cargo,'carbohydrate');runSeconds(a,60);assert.ok(a.state.pheromones.some(p=>p>0));assert.ok(a.state.stores.carbohydrate>start);});
test('the final food portion is collected exactly and never regenerates',()=>{
 const sim=new AntSimulation(99,1),ant=sim.state.ants[1];
 Object.assign(ant,{view:'surface',x:720,y:430,age:30,energy:1,hunger:0,cargo:null});
 const food={id:sim.state.nextId++,x:725,y:430,kind:'protein' as const,amount:.3,initial:10,radius:20};
 sim.state.resources=[food];sim.context.rebuild(sim.state);runSeconds(sim,1);
 assert.equal(food.amount,0);assert.equal(ant.cargo,'protein');assert.equal(ant.amount,.3);
 assert.ok(sim.state.pheromones.some(p=>p>0),'Returning collector leaves real scent');
 runSeconds(sim,100);assert.equal(food.amount,0,'Source refilled itself');
 const restored=new AntSimulation();restored.command({type:'load',state:JSON.parse(sim.serialize())});
 assert.equal(restored.state.resources[0].amount,0);
});
test('surface ants never move through solid obstacles',()=>{const a=new AntSimulation(8,40);for(const ant of a.state.ants.slice(1)){ant.view='surface';ant.x=470;ant.y=304;ant.angle=0;ant.memory={x:600,y:304};}for(let i=0;i<3000;i++){a.step();for(const ant of a.state.ants)assert.ok(isOpen(a.state,ant,ant.view),`ant ${ant.id} inside wall at ${ant.x},${ant.y}`);}});
test('brood develops, queen produces eggs, and care responds locally',()=>{const a=new AntSimulation(10);a.state.stores.protein=300;a.state.stores.carbohydrate=300;const before=a.state.nextId;runSeconds(a,240);assert.ok(a.state.nextId>before);assert.ok(a.state.births>0,`No births: ${JSON.stringify(a.state.brood.slice(0,2))}`);validateSave(a.state);console.log(JSON.stringify({time:a.state.time,births:a.state.births,brood:a.state.brood.length,excavated:a.state.excavated,soil:a.state.depositedSoil,waste:a.state.removedWaste,food:a.state.stores}));});
test('starvation eventually causes mortality',()=>{const a=new AntSimulation(12,4);a.state.resources=[];a.state.stores={carbohydrate:0,protein:0,water:0};for(const ant of a.state.ants){ant.hunger=.99;ant.energy=.05;}runSeconds(a,30);assert.ok(a.state.deaths>0);});
console.log(`\n${passed} behavior checks passed.`);
for(const count of [200,1000,3000]){const a=new AntSimulation(71,count);const begin=performance.now();a.step(300);const elapsed=performance.now()-begin;console.log(`BENCH ${count} workers: ${(elapsed/300).toFixed(3)} ms/tick, ${Math.round(300000/elapsed)} ticks/s; ${a.state.ants.length} living ants`);}
test('digging transports soil and cleaning removes refuse',()=>{const a=new AntSimulation(10);runSeconds(a,120);assert.ok(a.state.excavated>0);assert.ok(a.state.depositedSoil>0);assert.ok(a.state.removedWaste>0);assert.ok(a.state.nest.reduce((sum,n)=>sum+n,0)>createColony(10).nest.reduce((sum,n)=>sum+n,0));});
test('brood is relocated toward better local conditions',()=>{const a=new AntSimulation(4,1),nurse=a.state.ants[1];a.state.settings.temperature=12;nurse.view='nest';nurse.x=490;nurse.y=540;nurse.z=100;nurse.age=1;nurse.task='nursing';nurse.energy=1;nurse.hunger=0;nurse.timer=13;a.state.brood=[{id:a.state.nextId++,x:490,y:540,z:100,stage:'pupa',progress:0,nutrition:1,care:.2,carriedBy:null}];nurse.carryingId=a.state.brood[0].id;nurse.target={x:490,y:540,z:100};nurse.decision=1;const startY=a.state.brood[0].y;runSeconds(a,80);assert.ok(a.state.brood[0].y<startY-50,`Brood stayed at ${a.state.brood[0].y}`);});
test('depleted resources are forgotten and trails fade without new food',()=>{const a=new AntSimulation(91,1),worker=a.state.ants[1];a.state.resources=[];worker.view='surface';worker.x=1050;worker.y=250;worker.memory={x:1050,y:250};worker.target={...worker.memory};worker.task='foraging';worker.decision=0;deposit(a.state,worker,10);runSeconds(a,1);assert.equal(worker.memory,null);runSeconds(a,100);assert.ok(a.state.pheromones.reduce((v,n)=>v+n,0)<2);});
test('local contact recruits nestmates without revealing distant food globally',()=>{const a=new AntSimulation(45,20);a.state.resources=[];for(const ant of a.state.ants.slice(1)){ant.view='surface';ant.x=1100;ant.y=800;ant.energy=1;ant.hunger=0;ant.memory=null;ant.target=null;ant.decision=0;ant.task='exploring';}const scout=a.state.ants[1];scout.memory={x:1200,y:700};scout.task='returning';scout.cargo='carbohydrate';scout.amount=.8;const isolated=a.state.ants[20];isolated.x=900;isolated.y=800;a.step();assert.ok(a.state.ants.slice(2,20).some(ant=>ant.memory?.x===1200),'No local recruitment');assert.equal(isolated.memory,null,'Distant ant learned food without contact');});
test('locally encountered brood needs change a worker task',()=>{const care=new AntSimulation(34,1),empty=new AntSimulation(34,1);for(const sim of [care,empty]){const ant=sim.state.ants[1];Object.assign(ant,{view:'nest',x:490,y:540,z:100,age:25,tendency:.5,task:'resting',timer:10,energy:1,hunger:0,decision:0,cargo:null});sim.state.brood=[];}care.state.brood=[{id:care.state.nextId++,x:490,y:540,z:100,stage:'larva',progress:0,nutrition:.2,care:.2,carriedBy:null}];care.step();empty.step();assert.equal(care.state.ants[1].task,'nursing');assert.notEqual(empty.state.ants[1].task,'nursing');assert.ok(care.state.brood[0].care>.2);});
test('3D galleries are connected across multiple depth layers',()=>{const s=createColony();assert.equal(s.nest.length,NEST_CELLS);const start=cellIndex(WORLD.nestEntrance),seen=new Set([start]),queue=[start];for(let i=0;i<queue.length;i++)for(const n of neighbors(queue[i]))if(s.nest[n]&&!seen.has(n)){seen.add(n);queue.push(n);}assert.equal(seen.size,s.nest.reduce((n,v)=>n+v,0),'Disconnected chamber');assert.ok(new Set(queue.map(i=>Math.floor(i/NEST_SLICE))).size>=5);});
test('a food carrier navigates between 3D layers without entering soil',()=>{const sim=new AntSimulation(42,1),ant=sim.state.ants[1];Object.assign(ant,{...NURSERY,view:'nest',task:'returning',cargo:'protein',amount:.8,hunger:0,energy:1});const before=sim.state.stores.protein;let changed=false;for(let i=0;i<2400;i++){sim.step();if(Math.abs(ant.z-NURSERY.z)>NEST_LAYER_SIZE/2)changed=true;assert.ok(isOpen(sim.state,ant,ant.view));}assert.ok(changed);assert.ok(sim.state.stores.protein>before);});
test('local sensing does not reach a distant depth layer',()=>{const index=new SpatialIndex<{x:number;y:number;z:number}>(40);index.rebuild([{x:100,y:100,z:20},{x:100,y:100,z:180}]);assert.equal(index.query({x:100,y:100,z:20},14).length,1);});
test('excavation opens an adjacent voxel on the third axis',()=>{const sim=new AntSimulation(3,1);let from=-1,to=-1;for(let i=0;i<sim.state.nest.length;i++)if(sim.state.nest[i]&&cellPoint(i).y>300){const n=neighbors(i).find(n=>Math.abs(n-i)===NEST_SLICE&&!sim.state.nest[n]);if(n!==undefined){from=i;to=n;break;}}assert.ok(from>=0);const ant=sim.state.ants[1];Object.assign(ant,{...cellPoint(from),view:'nest',task:'digging',target:cellPoint(to),decision:10,timer:0,cargo:null,energy:1,hunger:0});runSeconds(sim,9);assert.equal(sim.state.nest[to],1);assert.equal(sim.state.excavated,1);assert.equal(ant.cargo,'soil');});
test('version 1 saves migrate without resetting entities, time, or randomness',()=>{const s=createColony(77);const old=JSON.parse(JSON.stringify(s));old.version=1;old.nest=projectNest(s.nest);old.excavation=Array(NEST_SLICE).fill(0);for(const p of [...old.ants,...old.brood,...old.debris])delete p.z;const upgraded=validateSave(old);assert.equal(upgraded.version,3);assert.equal(upgraded.rng,s.rng);assert.equal(upgraded.time,s.time);assert.deepEqual(upgraded.ants.map(a=>a.id),s.ants.map(a=>a.id));assert.ok(upgraded.ants.every(a=>a.z===NEST_CENTER));assert.deepEqual(projectNest(upgraded.nest),old.nest);const a=new AntSimulation();a.command({type:'load',state:old});a.paused=false;runSeconds(a,20);validateSave(a.state);});
test('invalid 3D positions and volume shapes preserve the current colony',()=>{const sim=new AntSimulation();const before=sim.serialize(),bad=JSON.parse(before);bad.ants[0].z=355;assert.throws(()=>sim.command({type:'load',state:bad}));bad.ants[0].z=180;bad.nest.pop();assert.throws(()=>sim.command({type:'load',state:bad}));assert.equal(sim.serialize(),before);});
console.log(`TOTAL ${passed} behavior checks passed.`);
