import assert from 'node:assert/strict';
import { SolarEngine, Body, Vec, G, MAX_DAY, MIN_DAY, KM_S, dateDay, position, PLANETS, length, sub, energy, integrate } from '../lib/solar/engine';
let passed=0;
function test(name:string,fn:()=>void){fn();passed++;console.log(`PASS solar: ${name}`);}
const point=(id:string,mass:number,p:Vec,v:Vec,radius=1):Body=>({id,name:id,kind:'planet',mass,p,v,radius,color:'#fff',trail:[]});
test('J2000 Earth reference position and 1-AU orbit',()=>{const p=position(PLANETS[2],0);assert.ok(Math.abs(p[0]+.17717)<.0001);assert.ok(Math.abs(p[1]-.96721)<.0001);assert.ok(length(p)>.98&&length(p)<1.02);});
test('reference planets, moons, date range, and exact pause',()=>{const s=new SolarEngine(0);assert.equal(s.bodies.length,14);const before=JSON.stringify(s.bodies);s.paused=true;assert.equal(s.tick(5),0);assert.equal(JSON.stringify(s.bodies),before);assert.throws(()=>s.reset(NaN));assert.throws(()=>s.reset(MAX_DAY+1));assert.throws(()=>s.reset(MIN_DAY-1));s.reset(MAX_DAY-.1);s.tick(10);assert.equal(s.day,MAX_DAY);assert.equal(s.paused,true);});
test('switching to gravity preserves relative state and removes bulk motion',()=>{const s=new SolarEngine(0);const earth=s.bodies.find(b=>b.id==='earth')!;const old=[...earth.p] as Vec;s.experiment();const sun=s.bodies.find(b=>b.id==='sun')!;assert.ok(length(sub(sub(earth.p,sun.p),old))<1e-14);for(let k=0;k<3;k++)assert.ok(Math.abs(s.bodies.reduce((a,b)=>a+b.v[k]*b.mass,0))<1e-15);});
test('a one-year circular orbit conserves energy and returns near its start',()=>{const bodies=[point('sun',1,[0,0,0],[0,0,0],695700),point('earth',3e-6,[1,0,0],[0,Math.sqrt(G),0],6371)];const initial=energy(bodies);for(let n=0;n<36525;n++)integrate(bodies,.01);assert.ok(Math.abs((energy(bodies)-initial)/initial)<1e-7);assert.ok(length(sub(sub(bodies[1].p,bodies[0].p),[1,0,0]))<.002);});
test('physical collision merges mass and conserves momentum',()=>{const s=new SolarEngine(0);s.mode='experiment';s.bodies=[point('a',1,[0,0,0],[.2,0,0],1000),point('b',.5,[1e-8,0,0],[-.1,0,0],1000)];s.collisions();assert.equal(s.bodies.length,1);assert.equal(s.bodies[0].mass,1.5);assert.ok(Math.abs(s.bodies[0].v[0]-.1)<1e-12);});
test('removing the Sun leaves objects moving freely in a force-free system',()=>{const s=new SolarEngine(0);s.experiment();s.bodies=[point('sun',1,[0,0,0],[0,0,0]),point('probe',0,[1,0,0],[0,.01,0])];s.remove('sun');s.tick(1);assert.ok(Math.abs(s.bodies[0].p[1]-.01)<1e-12);});
test('edits, launch validation, body limit, and reset',()=>{const s=new SolarEngine(0);s.setMass('jupiter',.002);assert.equal(s.mode,'experiment');assert.equal(s.bodies.find(b=>b.id==='jupiter')!.mass,.002);assert.throws(()=>s.setMass('sun',NaN));assert.throws(()=>s.velocity('earth',Infinity));assert.throws(()=>s.move('earth',[101,0,0]));assert.throws(()=>s.launch([NaN,0,0],[0,0,0],'probe'));const id=s.launch([2,0,0],[0,.02,0],'probe');assert.equal(s.bodies.find(b=>b.id===id)!.mass,0);while(s.bodies.length<50)s.launch([2,0,0],[0,0,0],'probe');assert.throws(()=>s.launch([2,0,0],[0,0,0],'probe'));s.reset(0);assert.equal(s.bodies.length,14);assert.equal(s.mode,'explore');});
test('all four scenarios start paused and remain finite while advancing',()=>{for(const id of ['earth-speed','jupiter-comet','binary','mars-launch'] as const){const s=new SolarEngine(dateDay('2026-09-18'));s.scenario(id);assert.equal(s.mode,'experiment');assert.equal(s.paused,true);const start=s.day;s.paused=false;for(let n=0;n<40;n++)s.tick(.2,1000);assert.ok(s.day>start+7.9);assert.ok(s.bodies.every(b=>[...b.p,...b.v].every(Number.isFinite)));}});
test('identical starting states and edits reproduce identical gravity steps',()=>{const a=new SolarEngine(0),b=new SolarEngine(0);for(const s of [a,b]){s.experiment();s.velocity('earth',1.2);for(let i=0;i<30;i++)s.tick(.1);}assert.deepEqual(a.bodies,b.bodies);});
test('higher Earth speed increases its orbital energy',()=>{const s=new SolarEngine(0);s.experiment();const b=s.bodies.find(b=>b.id==='earth')!,v=length(b.v);s.velocity('earth',1.35);assert.ok(length(b.v)>v*1.3);assert.ok(length(b.v)*KM_S>35);});
console.log(`TOTAL ${passed} solar physics checks passed.`);
