'use client';
import { useLanguage, useT } from '@/lib/i18n/language';
import {useEffect,useRef,useState} from 'react';
import {Download,Upload,Save,FolderOpen,Clock} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Command,Snapshot} from '@/lib/simulation/types';
import {listColonies,saveColony,SavedColony} from '@/lib/simulation/storage';
import {toast} from 'sonner';
export default function SaveDialog({open,onOpenChange,dispatch}:{open:boolean;onOpenChange:(v:boolean)=>void;dispatch:(c:Command)=>Promise<Snapshot>}){
 const tr = useT();
 const { language } = useLanguage();
 const [name,setName]=useState('');const [saved,setSaved]=useState<SavedColony[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const file=useRef<HTMLInputElement>(null);const [exportData,setExportData]=useState<{url:string;name:string;json:string}|null>(null);
 useEffect(()=>()=>{if(exportData)URL.revokeObjectURL(exportData.url);},[exportData]);
 const refresh=()=>listColonies().then(setSaved).catch(e=>setError(e.message));useEffect(()=>{if(open){setError(null);void refresh();}},[open]);
 async function namedSave(){if(!name.trim()||busy)return;setBusy(true);try{const s=await dispatch({type:'snapshot'});await saveColony({id:crypto.randomUUID(),name:name.trim().slice(0,80),savedAt:Date.now(),state:s.state});toast.success(tr('Colony saved in this browser'));await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 async function exportFile(){setBusy(true);setError(null);try{const s=await dispatch({type:'snapshot'});const json=JSON.stringify(s.state);setExportData({url:URL.createObjectURL(new Blob([json],{type:'application/json'})),name:`ant-colony-${s.state.seed}-${Math.floor(s.state.time)}s.json`,json});}catch(e){setError(e instanceof Error?e.message:'Could not prepare an export. Please try again.');}finally{setBusy(false);}}

 async function load(record:SavedColony){setBusy(true);setError(null);try{await dispatch({type:'load',state:record.state});toast.success(tr('Colony restored and paused'));onOpenChange(false);}catch(e){setError(e instanceof Error?e.message:'Could not restore this colony.');}finally{setBusy(false);}}
 async function importFile(f:File){setBusy(true);setError(null);try{if(f.size>20*1024*1024)throw new Error('Choose a colony file smaller than 20 MB.');let data:unknown;try{data=JSON.parse(await f.text());}catch{throw new Error('This file is not readable JSON. Your current colony is unchanged.');}await dispatch({type:'load',state:data});toast.success(tr('Colony imported and paused'));onOpenChange(false);}catch(e){setError(e instanceof Error?e.message:'Import failed.');}finally{setBusy(false);if(file.current)file.current.value='';}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="save-dialog"><DialogHeader><DialogTitle>{tr("Your colonies")}</DialogTitle><DialogDescription>{tr("Saved on this device. Export a copy to move a colony elsewhere.")}</DialogDescription></DialogHeader><div className="save-form"><Input aria-label={tr("Colony name")} maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder={tr("Colony name")} onKeyDown={e=>{if(e.key==='Enter')void namedSave();}}/><button className="button primary" disabled={busy||!name.trim()} onClick={()=>void namedSave()}><Save size={15}/>{tr("Save")}</button></div>{error&&<p className="error-message" role="alert">{tr(error)}</p>}<div className="save-list">{saved.length?saved.map(s=><div key={s.id} className="save-row"><div><strong>{s.id==='autosave'?<Clock size={15}/>:<FolderOpen size={15}/>} {s.id === 'autosave' ? tr('Last session') : s.name}</strong><span>{tr(s.state.ants.filter(a=>a.task!=='queen').length)}{tr(" workers · ")}{tr(new Date(s.savedAt).toLocaleString(language === 'el' ? 'el-GR' : 'en-GB'))}</span></div><button className="button secondary" disabled={busy} onClick={()=>void load(s)}>{tr("Load")}</button></div>):<p className="muted small">{tr("No colonies saved yet. A rolling autosave is kept every 30 seconds.")}</p>}</div><div className="export-row"><button className="button secondary" disabled={busy} onClick={()=>void exportFile()}><Download size={15}/>{tr("Export file")}</button><button className="button secondary" disabled={busy} onClick={()=>file.current?.click()}><Upload size={15}/>{tr("Import file")}</button><input ref={file} className="sr-only" type="file" accept=".json,application/json" aria-label={tr("Import colony file")} onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);}}/></div>{exportData&&<div className="export-ready"><span>{tr("Snapshot ready · ")}{tr(Math.round(exportData.json.length/1024))}{tr(" KB")}</span><div><a className="button primary" href={exportData.url} download={exportData.name}><Download size={15}/>{tr("Download JSON")}</a><button className="button secondary" onClick={()=>{void navigator.clipboard.writeText(exportData.json).then(()=>toast.success(tr('Colony JSON copied'))).catch(()=>setError('Clipboard access is unavailable. Use Download JSON instead.'));}}>{tr("Copy JSON")}</button></div></div>}<p className="muted small">{tr("Loading replaces the current view and pauses the colony. Save your current colony first if you want to keep both.")}</p></DialogContent></Dialog>;
}
