'use client';
import { useEffect, useRef } from 'react';
import { Ant, ColonyState, Snapshot, View } from '@/lib/simulation/types';
import { Camera, renderWorld } from '@/lib/simulation/renderer';
export type CanvasControls={zoom:(factor:number)=>void;fit:()=>void};
export default function WorldCanvas({state,liveSnapshot,view,pheromones,activity,conditions,selected,follow,onSelect,onPlace,tool,controls,onPerformance}:{state:ColonyState;liveSnapshot?:React.RefObject<Snapshot|null>;view:View;pheromones:boolean;activity:boolean;conditions:boolean;selected:number|null;follow:boolean;onSelect:(id:number|null)=>void;onPlace:(x:number,y:number)=>void;tool:string;controls:React.RefObject<CanvasControls|null>;onPerformance?:(fps:number,ms:number)=>void}){
 const ref=useRef<HTMLCanvasElement>(null);const latest=useRef({state,view,pheromones,activity,conditions,selected,follow,onSelect,onPlace,tool,onPerformance});latest.current={state,view,pheromones,activity,conditions,selected,follow,onSelect,onPlace,tool,onPerformance};
 const cameras=useRef<Record<View,Camera>>({surface:{x:680,y:430,zoom:1},nest:{x:680,y:420,zoom:1}});
 useEffect(()=>{const canvas=ref.current!,c=canvas.getContext('2d')!;let frame=0,w=0,h=0,scale=1;let frames=0,total=0,last=performance.now();let lastState=latest.current.state,previousTime=lastState.time,arrived=performance.now();let previousAnts=new Map<number,Ant>();const pointers=new Map<number,{x:number;y:number}>();let start={x:0,y:0},dragged=false,lastDistance=0;
 const size=()=>{const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio,2);canvas.width=w*d;canvas.height=h*d;c.setTransform(d,0,0,d,0,0);};const obs=new ResizeObserver(size);obs.observe(canvas);size();
 const zoom=(factor:number)=>{const cam=cameras.current[latest.current.view];cam.zoom=Math.max(.45,Math.min(6,cam.zoom*factor));};controls.current={zoom,fit:()=>{cameras.current[latest.current.view]={x:680,y:420,zoom:1};}};
 const draw=()=>{const p={...latest.current,state:liveSnapshot?.current?.state??latest.current.state},cam=cameras.current[p.view];if(p.follow&&p.selected!==null){const ant=p.state.ants.find(a=>a.id===p.selected);if(ant?.view===p.view){cam.x=ant.x;cam.y=ant.y;}}const t=performance.now();if(p.state.tick!==lastState.tick||p.state.seed!==lastState.seed){previousAnts=new Map(lastState.ants.map(a=>[a.id,a]));previousTime=lastState.time;lastState=p.state;arrived=t;}const blend=Math.min(1,(t-arrived)/100);scale=renderWorld(c,w,h,p.state,{...p,camera:cam,time:previousTime+(p.state.time-previousTime)*blend,previousAnts,blend});total+=performance.now()-t;frames++;if(t-last>1000){p.onPerformance?.(Math.round(frames*1000/(t-last)),total/frames);last=t;frames=0;total=0;}frame=requestAnimationFrame(draw);};frame=requestAnimationFrame(draw);
 const down=(e:PointerEvent)=>{canvas.focus();canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});start={x:e.clientX,y:e.clientY};dragged=false;if(pointers.size===2){const a=[...pointers.values()];lastDistance=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);}};
 const move=(e:PointerEvent)=>{const prev=pointers.get(e.pointerId);if(!prev)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const a=[...pointers.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(lastDistance)zoom(dist/lastDistance);lastDistance=dist;dragged=true;return;}if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>4)dragged=true;const cam=cameras.current[latest.current.view];cam.x-=(e.clientX-prev.x)/scale;cam.y-=(e.clientY-prev.y)/scale;cam.x=Math.max(0,Math.min(1400,cam.x));cam.y=Math.max(0,Math.min(900,cam.y));};
 const up=(e:PointerEvent)=>{pointers.delete(e.pointerId);if(dragged||e.type==='pointercancel')return;const p={...latest.current,state:liveSnapshot?.current?.state??latest.current.state},r=canvas.getBoundingClientRect(),cam=cameras.current[p.view];const x=(e.clientX-r.left-w/2)/scale+cam.x,y=(e.clientY-r.top-h/2)/scale+cam.y;if(p.tool!=='select'){p.onPlace(x,y);return;}let closest=null,dist=18/scale;for(const a of p.state.ants){if(a.view!==p.view||!a.alive)continue;const d=Math.hypot(a.x-x,a.y-y);if(d<dist){closest=a.id;dist=d;}}p.onSelect(closest);};
 const wheel=(e:WheelEvent)=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.001));};const key=(e:KeyboardEvent)=>{const cam=cameras.current[latest.current.view];if(e.key==='+'||e.key==='=')zoom(1.2);else if(e.key==='-')zoom(1/1.2);else if(e.key==='ArrowLeft')cam.x-=30/scale;else if(e.key==='ArrowRight')cam.x+=30/scale;else if(e.key==='ArrowUp')cam.y-=30/scale;else if(e.key==='ArrowDown')cam.y+=30/scale;else if(e.key==='Enter'){const p=latest.current;p.onSelect(p.state.ants.find(a=>a.alive&&a.view===p.view)?.id??null);}else return;e.preventDefault();};
 canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('wheel',wheel,{passive:false});canvas.addEventListener('keydown',key);
 return()=>{cancelAnimationFrame(frame);obs.disconnect();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);canvas.removeEventListener('wheel',wheel);canvas.removeEventListener('keydown',key);controls.current=null;};},[controls,liveSnapshot]);
 return <canvas ref={ref} className={`world-canvas tool-${tool}`} tabIndex={0} role="img" aria-label={`${view==='surface'?'Surface habitat':'Underground nest'} with ${state.ants.filter(a=>a.alive&&a.view===view).length} ants. Drag to pan, scroll to zoom, click an ant to inspect. Arrow keys pan, plus and minus zoom, Enter selects an ant.`}/>;
}
