'use client';
import { useEffect, useRef, useState } from 'react';
import { useT } from '@/lib/i18n/language';
import { BUILD_COST, BUS_ROUTE, CityEngine, ROADS, clockTime, type BuildingKind } from '@/lib/city/engine';
import { AUTO_KEY, comparePolicies, readSaves, saveCity, type CitySave, type Comparison } from '@/lib/city/storage';
import type { Selection } from '@/lib/city/renderer';

export default function CityWorkbench({ active = true, engine, selection, onSelect, onChange, onMessage }: { active?: boolean; engine: CityEngine; selection: Selection; onSelect: (selection: Selection) => void; onChange: () => void; onMessage: (message: string) => void }) {
  const tr = useT(), [tab, setTab] = useState('build');
  const [kind, setKind] = useState<BuildingKind>('home'), [fallbackPlot, setPlot] = useState(3), [fallbackRoad, setRoad] = useState('0-1'), [fallbackStop, setStop] = useState(11);
  const [name, setName] = useState('My Linden'), [saves, setSaves] = useState<CitySave[]>([]), [pending, setPending] = useState<CitySave | null>(null), [overwrite, setOverwrite] = useState(false);
  const [baseline, setBaseline] = useState<string | null>(null), [minutes, setMinutes] = useState(120), [busy, setBusy] = useState(false), [result, setResult] = useState<Comparison | null>(null);
  const abort = useRef<AbortController | null>(null), file = useRef<HTMLInputElement>(null);
  const autoAllowed = useRef(true);
  const initialized = useRef(false), latest = useRef({ onChange, onMessage }); 
  useEffect(() => { latest.current = { onChange, onMessage }; }, [onChange, onMessage]);
  const run = (action: () => void) => { try { action(); onChange(); } catch (error) { onMessage(error instanceof Error ? error.message : 'The change could not be completed.'); } };
  const plot = selection?.kind === 'building' ? selection.id : fallbackPlot;
  const road = selection?.kind === 'road' ? ROADS[selection.id].key : fallbackRoad;
  const stop = selection?.kind === 'stop' ? selection.id : fallbackStop;
  useEffect(() => {
    let cancelled = false;
    // Hydrate browser storage after the client commits; ignore abandoned mounts.
    queueMicrotask(() => {
      if (cancelled || initialized.current) return; initialized.current = true;
      try { setSaves(readSaves(localStorage)); const saved = localStorage.getItem(AUTO_KEY); if (saved) { engine.restore(saved); latest.current.onMessage('Your local autosave was restored. Press play when you are ready.'); latest.current.onChange(); } }
      catch (error) { autoAllowed.current = false; latest.current.onMessage(error instanceof Error ? error.message : 'Local storage is unavailable. Use Export city to keep a copy.'); }
    });
    return () => { cancelled = true; };
  }, [engine]);
  useEffect(() => {
    if (!active) { abort.current?.abort(); return; }
    let failed = false;
    const autosave = () => { if (!autoAllowed.current) return; try { localStorage.setItem(AUTO_KEY, engine.checkpoint()); } catch { if (!failed) latest.current.onMessage('Autosave could not write to browser storage. Export your city to keep it.'); failed = true; } };
    const timer = window.setInterval(autosave, 30000); window.addEventListener('pagehide', autosave);
    return () => { window.clearInterval(timer); window.removeEventListener('pagehide', autosave); autosave(); abort.current?.abort(); };
  }, [active, engine]);
  const persist = () => run(() => { const snapshot = JSON.parse(engine.checkpoint()); snapshot.name = name.trim(); const next = saveCity(localStorage, name, JSON.stringify(snapshot)); engine.state.name = name.trim(); autoAllowed.current = true; setSaves(next); setOverwrite(false); onMessage(`Saved “${name.trim()}” in this browser.`); });
  const compare = async () => { if (!baseline) return; const controller = new AbortController(); abort.current = controller; setBusy(true); setResult(null); try { const value = await comparePolicies(baseline, { ...engine.state.policies }, minutes, undefined, controller.signal); if (!controller.signal.aborted) setResult(value); } catch (error) { if (!controller.signal.aborted) onMessage(error instanceof Error ? error.message : 'Comparison failed.'); } finally { setBusy(false); } };
  const describePolicies = (p: CityEngine['state']['policies']) => `${p.buses} ${tr('buses')} · ${tr('fare')} ¤${p.fare} · ${tr('tax')} ${p.tax}% · ${tr('services')} ${p.services}% · ${tr(p.rain ? 'Rainy' : 'Clear skies')} · ${tr(p.roadClosed ? 'Market Street closed' : 'Market Street open')}`;
  const toolTabs = ['build', 'economy', 'saves', 'compare'];
  const b = engine.state.buildings[plot], population = engine.metrics().population;
  return <details className="city-workbench" open><summary>{tr('Shape your city')} <span>{tr('Build · local saves · fair comparisons')}</span></summary>
    <div className="city-workbench-tabs" role="tablist" aria-label={tr('City tools')}>{toolTabs.map((value, index) => <button id={`city-tool-${value}`} aria-controls="city-tool-panel" tabIndex={tab === value ? 0 : -1} onKeyDown={event => { const next = event.key === 'ArrowRight' ? (index + 1) % 4 : event.key === 'ArrowLeft' ? (index + 3) % 4 : event.key === 'Home' ? 0 : event.key === 'End' ? 3 : -1; if (next >= 0) { event.preventDefault(); setTab(toolTabs[next]); event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('button')[next]?.focus(); } }} role="tab" aria-selected={tab === value} key={value} onClick={() => setTab(value)}>{tr(value === 'build' ? 'Build' : value === 'economy' ? 'Growth & economy' : value === 'saves' ? 'Local saves' : 'Compare policies')}</button>)}</div>
    <div className="city-workbench-body" id="city-tool-panel" role="tabpanel" aria-labelledby={`city-tool-${tab}`}>
      {tab === 'build' && <><div className="city-tool-row"><label>{tr('Plot')}<select aria-label={tr('Construction plot')} value={plot} onChange={e => { setPlot(+e.target.value); onSelect({ kind: 'building', id: +e.target.value }); }}>{engine.state.buildings.map(b => <option key={b.id} value={b.id}>{b.id + 1} · {tr(b.name)}</option>)}</select></label><label>{tr('Build')}<select aria-label={tr('Building type')} value={kind} onChange={e => setKind(e.target.value as BuildingKind)}>{Object.entries(BUILD_COST).map(([k, cost]) => <option key={k} value={k}>{tr(k === 'empty' ? 'Clear plot' : k === 'home' ? 'Homes' : k === 'office' ? 'Office' : k === 'shop' ? 'Shop' : k === 'park' ? 'Park' : 'Public service')} · ¤{cost}</option>)}</select></label><button className="button secondary" onClick={() => run(() => { engine.setPaused(true); engine.build(plot, kind); onSelect({ kind: 'building', id: plot }); onMessage(`Plot ${plot + 1} updated. Construction cost ¤${BUILD_COST[kind]}.`); })}>{tr('Build on selected plot')}</button><span>{tr(b.name)} · {tr(engine.hasAccess(plot) ? 'Road access' : 'No road access')}</span></div>
      <div className="city-tool-row"><label>{tr('Street segment')}<select aria-label={tr('Street segment')} value={road} onChange={e => { setRoad(e.target.value); onSelect({ kind: 'road', id: ROADS.findIndex(r => r.key === e.target.value) }); }}>{ROADS.map(r => <option key={r.key} value={r.key}>{r.key} · {tr(engine.state.roads.includes(r.key) ? 'Built' : 'Missing')}</option>)}</select></label><button className="button secondary" onClick={() => run(() => { engine.setPaused(true); engine.toggleRoad(road); onMessage('Street network updated. Residents are replanning their journeys.'); })}>{tr(engine.state.roads.includes(road) ? 'Remove street · ¤50' : 'Build street · ¤250')}</button><label>{tr('Loop stop')}<select aria-label={tr('Loop stop')} value={stop} onChange={e => { setStop(+e.target.value); onSelect({ kind: 'stop', id: +e.target.value }); }}>{BUS_ROUTE.map(n => <option key={n} value={n}>{n} · {tr(engine.state.busStops.includes(n) ? 'Stop present' : 'No stop')}</option>)}</select></label><button className="button secondary" onClick={() => run(() => { engine.setPaused(true); engine.toggleStop(stop); onMessage('Loop stops updated.'); })}>{tr(engine.state.busStops.includes(stop) ? 'Remove stop · ¤250' : 'Add stop · ¤250')}</button></div><p>{tr('Select a building in either view or choose a plot above. Homes hold 8 residents; offices offer 22 jobs; shops offer 10. Occupied homes need replacement housing before redevelopment. The Loop streets stay connected.')}</p></>}
      {tab === 'economy' && <><div className="city-economy-grid"><div><strong>{population}</strong><span>{tr('Residents')}</span></div><div><strong>{engine.state.buildings.filter(b => b.kind === 'home').reduce((n, b) => n + b.capacity, 0) - population}</strong><span>{tr('Vacant homes')}</span></div><div><strong>{engine.state.arrivals} / {engine.state.departures}</strong><span>{tr('Arrivals / departures')}</span></div><div><strong>{engine.state.buildings.filter(b => !b.open).length}</strong><span>{tr('Closed businesses')}</span></div></div><p>{tr('At midnight, occupancy changes rents, businesses pay overhead, employers hire, and households pay bills. Available homes and jobs attract up to four newcomers per day. Two difficult days can make residents leave; two days in debt can close a business.')}</p><div className="city-event-list">{engine.state.events.slice(0, 4).map((event, i) => <p key={`${event.time}-${i}`}><time>{clockTime(event.time)}</time> {tr(event.text)}</p>)}</div></>}
      {tab === 'saves' && <><div className="city-tool-row"><label>{tr('Save name')}<input aria-label={tr('City save name')} maxLength={60} value={name} onChange={e => { setName(e.target.value); setOverwrite(false); }}/></label><button className="button secondary" onClick={() => saves.some(s => s.name === name.trim()) ? setOverwrite(true) : persist()}>{tr('Save city')}</button><button className="button secondary" onClick={() => run(() => { const blob = new Blob([engine.checkpoint()], { type: 'application/json' }), url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = 'city-life.json'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); })}>{tr('Export city')}</button><button className="button secondary" onClick={() => file.current?.click()}>{tr('Import city')}</button><input ref={file} hidden type="file" accept=".json,application/json" onChange={async e => { const selected = e.target.files?.[0]; e.target.value = ''; if (!selected) return; if (selected.size > 4000000) { onMessage('This city save is too large.'); return; } try { const snapshot = await selected.text(), test = new CityEngine(); test.restore(snapshot); setPending({ name: test.state.name, savedAt: Date.now(), snapshot }); } catch { onMessage('This file is not a valid city save. Your current city was kept.'); } }}/></div>
      {overwrite && <div className="city-save-confirm" role="alert">{tr('Replace the existing save with this city?')} <button onClick={persist}>{tr('Replace save')}</button><button onClick={() => setOverwrite(false)}>{tr('Cancel')}</button></div>}
      <div className="city-saves-list">{saves.map(save => <button key={save.name} onClick={() => setPending(save)}><strong>{save.name}</strong><small>{new Date(save.savedAt).toLocaleString()}</small><span>{tr('Load')}</span></button>)}</div>
      {pending && <div className="city-save-confirm" role="alert">{tr('Replace the current city with this saved city?')} <strong>{pending.name}</strong><button onClick={() => run(() => { engine.restore(pending.snapshot); autoAllowed.current = true; setName(pending.name); onSelect(null); setPending(null); onMessage('Saved city loaded and paused.'); })}>{tr('Load saved city')}</button><button onClick={() => setPending(null)}>{tr('Cancel')}</button></div>}
      <p>{tr('Autosaves every 30 seconds in this browser. Named saves stay separate. Export a JSON copy to keep your city outside browser storage; clearing browser data removes local saves.')}</p></>}
      {tab === 'compare' && <><div className="city-tool-row"><button className="button secondary" disabled={busy} onClick={() => { engine.setPaused(true); setBaseline(engine.checkpoint()); setResult(null); onChange(); onMessage('Comparison checkpoint captured. Change policies in the sidebar, then run both versions.'); }}>{tr(baseline ? 'Replace comparison checkpoint' : 'Capture comparison checkpoint')}</button><label>{tr('Elapsed time')}<select aria-label={tr('Comparison duration')} value={minutes} disabled={busy} onChange={e => setMinutes(+e.target.value)}><option value={120}>{tr('2 hours')}</option><option value={360}>{tr('6 hours')}</option><option value={1440}>{tr('1 day')}</option></select></label><button className="button secondary" disabled={!baseline || busy} onClick={compare}>{tr(busy ? 'Running both cities…' : 'Run fair comparison')}</button>{busy && <button onClick={() => abort.current?.abort()}>{tr('Cancel')}</button>}</div><p>{tr('A uses checkpoint policies. B uses your current sidebar policies. Both copies start with identical residents, streets and budgets and run for exactly the same duration. Your live city stays untouched.')}</p>
      {result && <><p role="status">{tr('Comparison complete')} · {result.minutes} {tr('minutes')} · {clockTime(result.start)} → {clockTime(result.baseline.time)}</p><div className="city-comparison-table"><table><thead><tr><th>{tr('Outcome')}</th><th>{tr('A · checkpoint')}</th><th>{tr('B · new policies')}</th><th>{tr('Change')}</th></tr></thead><tbody>{([['Happiness', result.baseline.metrics.happiness, result.changed.metrics.happiness, '%'], ['Average commute', result.baseline.metrics.commute, result.changed.metrics.commute, ' min'], ['Road emissions', result.baseline.metrics.pollution, result.changed.metrics.pollution, ''], ['City treasury', result.baseline.treasury, result.changed.treasury, ' ¤'], ['Residents', result.baseline.metrics.population, result.changed.metrics.population, ''], ['Completed trips', result.baseline.metrics.trips, result.changed.metrics.trips, '']] as [string, number, number, string][]).map(([label, a, b, unit]) => <tr key={label}><th>{tr(label)}</th><td>{a.toFixed(1)}{unit}</td><td>{b.toFixed(1)}{unit}</td><td>{b - a > 0 ? '+' : ''}{(b - a).toFixed(1)}{unit === '%' ? ' pp' : unit}</td></tr>)}</tbody></table></div><p>{tr('Commute averages include completed work trips only; delayed arrivals may fall outside a short run. Emissions show the final traffic level, not cumulative emissions. Happiness changes are percentage points.')}</p><p>{tr('Policies')} A: {describePolicies(result.baselinePolicies)} · B: {describePolicies(result.changedPolicies)}</p></>}
      </>}
    </div>
  </details>;
}
