'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Building2, Bus, ChevronRight, CircleHelp, CloudRain, Focus, Footprints, Heart, Layers3, MapPin, Minus, MousePointer2, Pause, Play, Plus, RotateCcw, Save, SkipForward, SlidersHorizontal, Sparkles, Sun, Target, Users, Wallet, X } from 'lucide-react';
import HubNavigation, { SimulatorId } from '@/components/hub-navigation';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarTrigger } from '@/components/ui/sidebar';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Progress } from '@/components/ui/progress';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import CityCanvas, { CityControls } from './city-canvas';
import { BUILDINGS, CityEngine, Layer, Metrics, Policies, clockTime, dayNumber } from '@/lib/city/engine';
import { COLORS, Selection } from '@/lib/city/renderer';
import './city.css';

type Scenario = 'morning' | 'transit' | 'rain' | 'closure';
const scenarios: { id: Scenario; title: string; description: string }[] = [
  { id: 'morning', title: 'The morning rush', description: 'The original town at 07:00. Watch the commute build and compare modes of travel.' },
  { id: 'transit', title: 'A free ride', description: 'Six buses and no fares. Will more residents leave their cars at home?' },
  { id: 'rain', title: 'A rainy day', description: 'Walking and driving slow down. Follow the knock-on effect on arrival times.' },
  { id: 'closure', title: 'The road is closed', description: 'Close a section of Market Street and see how residents reroute.' },
];
const money = (n: number) => `¤${Math.round(n).toLocaleString()}`;
export default function CityLife({ active, onNavigate }: { active: boolean; onNavigate: (id: SimulatorId) => void }) {
  const [engine] = useState(() => new CityEngine());
  const [, redraw] = useState(0); const refresh = () => redraw(n => n + 1);
  const controls = useRef<CityControls | null>(null);
  const [selection, setSelection] = useState<Selection>({ kind: 'citizen', id: 1 });
  const [follow, setFollow] = useState(false); const [layer, setLayer] = useState<Layer>('city');
  const [labels, setLabels] = useState(true); const [busRoute, setBusRoute] = useState(true);
  const [help, setHelp] = useState(false); const [experiments, setExperiments] = useState(false);
  const [confirm, setConfirm] = useState<Scenario | 'restore' | null>(null);
  const [checkpoint, setCheckpoint] = useState<{ snapshot: string; time: number } | null>(null);
  const [comparison, setComparison] = useState<{ metrics: Metrics; time: number; start: number } | null>(null);
  const [message, setMessage] = useState('');
  const s = engine.state, m = engine.metrics(), c = selection?.kind === 'citizen' ? s.citizens[selection.id] : undefined;
  const b = selection?.kind === 'building' ? BUILDINGS[selection.id] : undefined;
  const policy = <K extends keyof Policies>(key: K, value: Policies[K]) => { engine.setPolicy(key, value); refresh(); };
  const select = (next: Selection) => { setSelection(next); setFollow(false); };
  const reset = (which: Scenario | 'restore') => {
    if (which === 'restore' && checkpoint) { engine.restore(checkpoint.snapshot); setMessage('Checkpoint restored. Adjust a policy, then press play to start another run.'); }
    else { engine.reset(); if (which === 'transit') { engine.setPolicy('fare', 0); engine.setPolicy('buses', 6); } if (which === 'rain') engine.setPolicy('rain', true); if (which === 'closure') engine.setPolicy('roadClosed', true); setMessage('A fresh morning, with the same residents and starting budgets.'); }
    setSelection({ kind: 'citizen', id: 1 }); setFollow(false); controls.current?.fit(); setExperiments(false); refresh();
  };
  useEffect(() => {
    if (!active) return;
    const key = (e: KeyboardEvent) => { const t = e.target as HTMLElement; if (t.closest('input,textarea,button,[role="dialog"],[role="alertdialog"],[role="slider"],[role="combobox"],[role="tab"],[contenteditable="true"]')) return; if (e.code === 'Space') { e.preventDefault(); engine.setPaused(!engine.paused); redraw(n => n + 1); } if (e.key === 'Escape') setFollow(false); };
    window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key);
  }, [active, engine]);
  const night = s.time % 1440 < 360 || s.time % 1440 >= 1200;
  return <SidebarProvider style={{ '--sidebar-width': '264px' } as React.CSSProperties} className="app-shell city-shell">
    <Sidebar className="observatory-sidebar"><SidebarHeader className="brand"><div className="brand-symbol"><Building2 size={24}/></div><div><strong>simulation<span>hub</span></strong><small>A SPACE FOR CURIOSITY</small></div><SidebarTrigger className="mobile-sidebar-close" aria-label="Close city settings"/></SidebarHeader>
      <SidebarContent><HubNavigation current="city" onNavigate={onNavigate}/><div className="sidebar-divider"/>
        <div className="sidebar-section"><div className="section-title"><Bus size={16}/><span>The Loop · public transit</span></div>
          <Parameter label="Buses in service" value={s.policies.buses} suffix=" buses" max={6} onChange={n => policy('buses', n)}/>
          <Parameter label="Bus fare" value={s.policies.fare} prefix="¤" max={6} onChange={n => policy('fare', n)}/>
          <p className="city-sidebar-note">{s.policies.buses ? `${m.riding} aboard · ${m.waiting} waiting at stops` : 'Service is off. Residents use another way to travel.'}</p>
        </div><div className="sidebar-divider"/>
        <div className="sidebar-section"><div className="section-title"><SlidersHorizontal size={16}/><span>City policies</span></div>
          <Parameter label="Income tax" value={s.policies.tax} suffix="%" max={35} onChange={n => policy('tax', n)}/>
          <Parameter label="Public services" value={s.policies.services} suffix="%" max={100} step={5} onChange={n => policy('services', n)}/>
          <p className="city-sidebar-note">Services support well-being and residents without a job. Funding comes from the city treasury.</p>
        </div><div className="sidebar-divider"/>
        <div className="sidebar-section"><div className="section-title"><CloudRain size={16}/><span>Change the conditions</span></div>
          <Toggle label="Rain" checked={s.policies.rain} onChange={n => policy('rain', n)}/>
          <Toggle label="Close Market Street" checked={s.policies.roadClosed} onChange={n => policy('roadClosed', n)}/>
        </div><div className="sidebar-divider"/>
        <div className="sidebar-section"><div className="section-title"><Layers3 size={16}/><span>Map details</span></div><Toggle label="Building labels" checked={labels} onChange={setLabels}/><Toggle label="Bus route & stops" checked={busRoute} onChange={setBusRoute}/></div>
      </SidebarContent><SidebarFooter className="sidebar-bottom"><button onClick={() => setHelp(true)}><CircleHelp size={17}/>How this city works<span>↗</span></button><div className="version-line"><span>CITY LIFE</span><span>03</span></div></SidebarFooter>
    </Sidebar>
    <main className="workspace city-workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>Simulations</span><ChevronRight size={14}/><strong>City Life</strong></div><button className="button secondary" onClick={() => setExperiments(true)}><Sparkles size={16}/>Experiments</button></header>
      <div className="page-heading"><div><div className="title-row"><h1>A city with <span>a life of its own.</span></h1><span className="species-tag">LINDEN · AGENT SANDBOX</span></div><p>Follow a resident. Change a policy. Watch the city respond.</p></div><button className="icon-button" aria-label="About City Life" onClick={() => setHelp(true)}><CircleHelp size={20}/></button></div>
      {message && <div className="city-notice" role="status">{message}<button className="icon-button" aria-label="Dismiss city message" onClick={() => setMessage('')}><X size={15}/></button></div>}
      <section className="simulation-panel city-panel" aria-label="City simulation">
        <div className="world-topbar city-topbar"><div className="city-clock">{s.policies.rain ? <CloudRain size={19}/> : <Sun size={19}/>}<div><strong>{clockTime(s.time)}</strong><span>Day {dayNumber(s.time)} · {s.policies.rain ? 'Rainy' : night ? 'Night' : 'Clear skies'}</span></div></div>
          <div className="playback"><button className="icon-button pause-button" aria-label={engine.paused ? 'Play city simulation' : 'Pause city simulation'} onClick={() => { engine.setPaused(!engine.paused); refresh(); }}>{engine.paused ? <Play size={16}/> : <Pause size={16}/>}</button><button className="icon-button" aria-label="Advance city by 15 minutes" onClick={() => { engine.setPaused(true); engine.advance(15); refresh(); }}><SkipForward size={16}/></button><Select value={String(engine.speed)} onValueChange={n => { engine.setSpeed(Number(n)); refresh(); }}><SelectTrigger className="speed-select" aria-label="City simulation speed"><SelectValue/></SelectTrigger><SelectContent>{[1, 2, 4, 8].map(n => <SelectItem key={n} value={String(n)}>{n}× speed</SelectItem>)}</SelectContent></Select><button className="icon-button" aria-label="Reset city" onClick={() => setConfirm('morning')}><RotateCcw size={16}/></button></div>
        </div>
        <div className="city-stage"><div className="city-map-wrap"><CityCanvas engine={engine} active={active && !experiments && !help && !confirm} display={{ layer, labels, busRoute, selection, follow }} controlsRef={controls} onSelect={select} onChange={refresh} onPan={() => setFollow(false)}/>
          <div className="city-map-top"><span className="city-live"><i className={engine.paused ? 'paused' : ''}/>{engine.paused ? 'PAUSED' : 'LIVE CITY'}</span><Select value={layer} onValueChange={value => setLayer(value as Layer)}><SelectTrigger className="city-layer-select" aria-label="City map layer"><Layers3 size={14}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="city">City view</SelectItem><SelectItem value="traffic">Traffic</SelectItem><SelectItem value="happiness">Happiness</SelectItem><SelectItem value="pollution">Road emissions</SelectItem></SelectContent></Select></div>
          <div className="city-map-bottom"><span><MousePointer2 size={13}/>{follow && c ? `Following ${c.name.split(' ')[0]}` : 'Select a resident or building'}</span><div className="city-map-controls"><button aria-label="Zoom in on city" onClick={() => controls.current?.zoom(1.3)}><Plus size={16}/></button><button aria-label="Zoom out of city" onClick={() => controls.current?.zoom(1 / 1.3)}><Minus size={16}/></button><button aria-label="Fit city to view" onClick={() => controls.current?.fit()}><Focus size={16}/></button></div></div>
          <div className="city-legend">{layer === 'city' ? Object.entries(COLORS).map(([kind, color]) => <span key={kind}><i style={{ background: color }}/>{kind === 'home' ? 'Homes' : kind === 'office' ? 'Work' : kind === 'shop' ? 'Shops' : kind === 'park' ? 'Parks' : 'Services'}</span>) : <span>{layer === 'happiness' ? 'Home colors: green ≥ 70 · amber 50–69 · coral < 50 happiness' : layer === 'traffic' ? 'Road colors: green 0–1 · amber 2–3 · coral 4+ cars' : 'Brighter roads carry more cars · illustrative emissions'}</span>}</div>
        </div>
        <aside className="city-inspector" aria-label="City inspector"><div className="city-inspector-heading"><span className="city-kicker">{b ? 'BUILDING INSPECTOR' : 'A LIFE IN LINDEN'}</span>{b && <button className="icon-button" aria-label="Return to residents" onClick={() => select({ kind: 'citizen', id: 1 })}><Users size={16}/></button>}</div>
          {c ? <><Select value={String(c.id)} onValueChange={n => select({ kind: 'citizen', id: Number(n) })}><SelectTrigger className="city-resident-select" aria-label="Choose a resident"><SelectValue/></SelectTrigger><SelectContent>{s.citizens.map(person => <SelectItem key={person.id} value={String(person.id)}>{person.name}</SelectItem>)}</SelectContent></Select>
            <p className="city-resident-meta">{c.age} years · {BUILDINGS[c.home].district}</p><span className="city-activity">{c.trip ? c.trip.stage === 'waiting' ? 'Waiting for the bus' : c.trip.stage === 'riding' ? 'Riding the Loop' : c.trip.mode === 'car' ? 'Driving' : 'Walking' : c.activity === 'work' ? 'At work' : c.activity === 'home' ? 'At home' : c.activity === 'relaxing' ? 'In the park' : 'Shopping'}</span>
            <p className="city-reason">“{c.reason}”</p>
            <button className={`button city-follow ${follow ? 'following' : 'secondary'}`} onClick={() => setFollow(!follow)}><Target size={15}/>{follow ? 'Following · stop' : 'Follow this resident'}<ArrowUpRight size={14}/></button>
            <div className="city-needs"><Need label="Happiness" value={c.happiness}/><Need label="Energy" value={c.energy}/><Need label="Hunger" value={c.hunger} warning/></div>
            <dl className="city-details"><div><dt><Wallet size={13}/>Wallet</dt><dd>{money(c.money)}</dd></div><div><dt><MapPin size={13}/>Home</dt><dd><button onClick={() => select({ kind: 'building', id: c.home })}>{BUILDINGS[c.home].name}</button></dd></div><div><dt>Work</dt><dd>{c.job === null ? 'Between jobs' : BUILDINGS[c.job].name}</dd></div>{c.trip && <div><dt>Destination</dt><dd>{BUILDINGS[c.trip.destination].name}</dd></div>}<div><dt>Last commute</dt><dd>{c.commute ? `${Math.round(c.commute)} min` : 'Not yet today'}</dd></div></dl>
            <details className="city-journal" open><summary>Today’s moments</summary>{c.log.length ? c.log.slice(0, 4).map((entry, i) => <div key={`${entry.time}-${i}`}><time>{clockTime(entry.time)}</time><p>{entry.text}</p></div>) : <p>The day is just beginning. Moments appear as this resident makes decisions.</p>}</details>
          </> : b ? <><h2>{b.name}</h2><p className="city-resident-meta">{b.district} · {b.kind === 'office' ? 'Workplace' : b.kind}</p><div className="city-building-symbol" style={{ color: COLORS[b.kind] }}><Building2 size={42}/></div><p className="city-reason">{b.kind === 'home' ? 'A place to recharge. Residents pay daily housing and household costs, then plan the next day around their work and needs.' : b.kind === 'office' || b.kind === 'shop' ? 'Workers earn wages while they are here. Their income supports daily needs and contributes to the city through tax.' : b.kind === 'park' ? 'Residents visit after errands or during free time. Time outdoors improves happiness; rain sends them home.' : 'City services contribute to well-being and support people between jobs. Adjust funding in City policies.'}</p>
            <dl className="city-details"><div><dt>Here now</dt><dd>{s.citizens.filter(p => !p.trip && p.location === b.id).length} people</dd></div>{b.kind === 'home' && <><div><dt>Residents</dt><dd>{s.citizens.filter(p => p.home === b.id).length}</dd></div><div><dt>Household costs</dt><dd>¤32 / person / day</dd></div></>}{(b.kind === 'office' || b.kind === 'shop') && <div><dt>Employees</dt><dd>{s.citizens.filter(p => p.job === b.id).length}</dd></div>}</dl>
            <div className="city-building-residents">{s.citizens.filter(p => b.kind === 'home' ? p.home === b.id : !p.trip && p.location === b.id).slice(0, 8).map(person => <button key={person.id} onClick={() => select({ kind: 'citizen', id: person.id })}>{person.name}<ChevronRight size={14}/></button>)}</div>
          </> : <p>Select a resident or building on the map.</p>}
        </aside></div>
        <div className="city-metrics"><Metric icon={<Users size={15}/>} label="Residents" value={String(m.population)} note={`${m.employed} employed · ${m.population - m.employed} between jobs`}/><Metric icon={<Heart size={15}/>} label="Happiness" value={`${Math.round(m.happiness)}%`} note="Citywide well-being"><Trend values={s.history.map(v => v.happiness)}/></Metric><Metric icon={<Footprints size={15}/>} label="On the move" value={String(m.walking + m.driving + m.riding + m.waiting)} note={`${m.walking} walking · ${m.driving} driving · ${m.riding} on buses`}/><Metric icon={<Wallet size={15}/>} label="City treasury" value={money(s.treasury)} note={s.treasury < 0 ? 'Deficit · consider tax or service funding' : `${m.commute ? `${Math.round(m.commute)} min average commute` : 'Waiting for the first work arrivals'}`}/></div>
      </section>
      <footer className="workspace-footer city-footer"><span><i className="status-dot"/>{s.events[0]?.text}</span><span>{engine.paused ? 'Paused' : '8 simulated min / second at 1×'} · Session only</span></footer>
    </main>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent className="city-dialog"><DialogHeader><DialogTitle>Small choices. A living city.</DialogTitle><DialogDescription>Linden is a simplified, deterministic city sandbox. It illustrates connections; it is not a forecast of a real city.</DialogDescription></DialogHeader><div className="city-help"><h3>Follow the day</h3><p>Residents leave home for work, earn wages, buy groceries, visit parks, and return to rest. Select someone on the map or use the resident picker. Their journal explains what they are doing and why.</p><h3>Try a change</h3><p>More buses and cheaper fares encourage transit. Cars slow each other down on busy roads. Rain slows travel, and a closed road changes routes. Tax funds services; services support happiness and provide daily help to people between jobs.</p><h3>Run an experiment</h3><p>Open Experiments to save a checkpoint, pin a result, and restore the same starting point. Compare runs after the same elapsed time. Changes to transit affect the next trip; people already on their way continue unless service is withdrawn.</p><h3>Controls and limits</h3><p>Space pauses. Drag or arrow keys pan; scroll, pinch, or +/− zoom. Enter on the map selects the next resident. Switching simulations suspends this city. This first version has a fixed population and town layout; services and road emissions are simplified measures. Workplaces run every day. Checkpoints last for this visit only.</p></div></DialogContent></Dialog>
    <Dialog open={experiments} onOpenChange={setExperiments}><DialogContent className="city-dialog city-experiments"><DialogHeader><DialogTitle>What changes when…</DialogTitle><DialogDescription>Start with the same town and residents. Change one condition and watch what follows.</DialogDescription></DialogHeader><div className="city-scenarios">{scenarios.map((scenario, i) => <button key={scenario.id} onClick={() => setConfirm(scenario.id)}><span>0{i + 1}</span><div><h3>{scenario.title}</h3><p>{scenario.description}</p></div><ArrowUpRight size={18}/></button>)}</div><div className="city-checkpoint"><h3><Save size={16}/>Your experiment</h3><p>{checkpoint ? `Checkpoint: day ${dayNumber(checkpoint.time)}, ${clockTime(checkpoint.time)}. Kept for this visit.` : 'Save a starting point, run the city, then pin the result. Restore your checkpoint to try a different policy.'}</p><div className="city-checkpoint-actions"><button className="button secondary" onClick={() => { setCheckpoint({ snapshot: engine.checkpoint(), time: s.time }); setComparison(null); setMessage('Checkpoint saved for this visit.'); }}>{checkpoint ? 'Replace checkpoint' : 'Save checkpoint'}</button><button className="button secondary" disabled={!checkpoint} onClick={() => setConfirm('restore')}>Restore</button><button className="button secondary" disabled={!checkpoint} onClick={() => { setComparison({ metrics: m, time: s.time, start: checkpoint!.time }); setMessage('Result pinned. Restore your checkpoint to try another policy.'); }}>Pin result</button></div>
      {comparison && <div className="city-comparison"><div><span>Measure</span><span>Pinned run</span><span>Current run</span></div><div><span>Elapsed time</span><span>{Math.round(comparison.time - comparison.start)} min</span><span>{Math.round(s.time - comparison.start)} min</span></div><div><span>Happiness</span><span>{Math.round(comparison.metrics.happiness)}%</span><span>{Math.round(m.happiness)}%</span></div><div><span>Avg. commute</span><span>{comparison.metrics.commute ? `${Math.round(comparison.metrics.commute)} min` : 'No arrivals'}</span><span>{m.commute ? `${Math.round(m.commute)} min` : 'No arrivals'}</span></div><div><span>Cars in motion</span><span>{comparison.metrics.driving}</span><span>{m.driving}</span></div><p><ArrowDownRight size={14}/>Compare at the same elapsed time for a useful result.</p></div>}</div></DialogContent></Dialog>
    <AlertDialog open={confirm !== null} onOpenChange={open => { if (!open) setConfirm(null); }}><AlertDialogContent className="city-dialog"><AlertDialogHeader><AlertDialogTitle>{confirm === 'restore' ? 'Return to your checkpoint?' : 'Start a fresh morning?'}</AlertDialogTitle><AlertDialogDescription>{confirm === 'restore' ? 'This replaces the current city with your saved starting point and pauses time. Your pinned result remains available.' : 'The current city will restart at 07:00 with the same residents. Your session checkpoint and pinned result remain available.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep exploring</AlertDialogCancel><AlertDialogAction onClick={() => { if (confirm) reset(confirm); setConfirm(null); }}>{confirm === 'restore' ? 'Restore checkpoint' : 'Start scenario'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </SidebarProvider>;
}
function Parameter({ label, value, max, onChange, prefix = '', suffix = '', step = 1 }: { label: string; value: number; max: number; onChange: (n: number) => void; prefix?: string; suffix?: string; step?: number }) { return <div className="parameter city-parameter"><div><label>{label}</label><output>{prefix}{value}{suffix}</output></div><Slider aria-label={label} value={[value]} min={0} max={max} step={step} onValueChange={values => onChange(values[0])}/></div>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="layer-toggle city-toggle"><span>{label}</span><Switch aria-label={label} checked={checked} onCheckedChange={onChange}/></label>; }
function Need({ label, value, warning = false }: { label: string; value: number; warning?: boolean }) { return <div className={`city-need ${warning ? 'hunger' : ''}`}><div><span>{label}</span><output>{Math.round(value)}%</output></div><Progress value={value} aria-label={label}/></div>; }
function Metric({ icon, label, value, note, children }: { icon: React.ReactNode; label: string; value: string; note: string; children?: React.ReactNode }) { return <div className="city-metric"><span>{icon}{label}</span><div><strong>{value}</strong>{children}</div><p>{note}</p></div>; }
function Trend({ values }: { values: number[] }) { const recent = values.slice(-48); return <svg className="city-trend" viewBox="0 0 100 32" aria-label="Happiness history" role="img"><polyline fill="none" stroke="currentColor" strokeWidth="1.5" points={recent.map((n, i) => `${i / Math.max(1, recent.length - 1) * 100},${31 - n * .3}`).join(' ')}/></svg>; }
