'use client';
import { useLanguage, useT } from '@/lib/i18n/language';
import { Suspense, lazy, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Building2, Box, Bus, ChevronRight, CircleHelp, CloudRain, Focus, Footprints, Heart, Layers3, MapPin, Minus, MousePointer2, Pause, Play, Plus, RotateCcw, RotateCw, SkipForward, SlidersHorizontal, Sparkles, Sun, Target, Users, Wallet, X } from 'lucide-react';
import HubNavigation, { SimulatorId } from '@/components/hub-navigation';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarTrigger } from '@/components/ui/sidebar';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { Progress } from '@/components/ui/progress';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import CityCanvas, { CityControls } from './city-canvas';
import { CityEngine, Layer, Policies, clockTime, dayNumber } from '@/lib/city/engine';
import { COLORS, Selection } from '@/lib/city/renderer';
import CityWorkbench from './city-workbench';
import './city.css';
const CityThree = lazy(() => import('./city-three'));

type Scenario = 'morning' | 'transit' | 'rain' | 'closure';
const scenarios: { id: Scenario; title: string; description: string }[] = [
  { id: 'morning', title: 'The morning rush', description: 'The original town at 07:00. Watch the commute build and compare modes of travel.' },
  { id: 'transit', title: 'A free ride', description: 'Six buses and no fares. Will more residents leave their cars at home?' },
  { id: 'rain', title: 'A rainy day', description: 'Walking and driving slow down. Follow the knock-on effect on arrival times.' },
  { id: 'closure', title: 'The road is closed', description: 'Close a section of Market Street and see how residents reroute.' },
];
const money = (n: number) => `¤${Math.round(n).toLocaleString()}`;
export default function CityLife({ active, onNavigate }: { active: boolean; onNavigate: (id: SimulatorId) => void }) {
 const tr = useT();
 const { language } = useLanguage();
  const [engine] = useState(() => new CityEngine());
  const [, redraw] = useState(0); const refresh = () => redraw(n => n + 1);
  const mapControls = useRef<CityControls | null>(null);
  const threeControls = useRef<CityControls | null>(null);
  const [view, setView] = useState<'3d' | 'map'>('3d');
  const [threeUnavailable, setThreeUnavailable] = useState(false);
  const controls = view === '3d' ? threeControls : mapControls;
  const [selection, setSelection] = useState<Selection>({ kind: 'citizen', id: 1 });
  const [follow, setFollow] = useState(false); const [layer, setLayer] = useState<Layer>('city');
  const [labels, setLabels] = useState(true); const [busRoute, setBusRoute] = useState(true);
  const [help, setHelp] = useState(false); const [experiments, setExperiments] = useState(false);
  const [confirm, setConfirm] = useState<Scenario | null>(null);
  const [message, setMessage] = useState('');
  const s = engine.state, m = engine.metrics(), c = selection?.kind === 'citizen' ? s.citizens[selection.id] : undefined;
  const b = selection?.kind === 'building' ? s.buildings[selection.id] : undefined;
  const policy = <K extends keyof Policies>(key: K, value: Policies[K]) => { engine.setPolicy(key, value); refresh(); };
  const select = (next: Selection) => { setSelection(next); setFollow(false); };
  const reset = (which: Scenario) => {
    engine.reset(); if (which === 'transit') { engine.setPolicy('fare', 0); engine.setPolicy('buses', 6); } if (which === 'rain') engine.setPolicy('rain', true); if (which === 'closure') engine.setPolicy('roadClosed', true); setMessage('A fresh morning, with the same residents and starting budgets.');
    setSelection({ kind: 'citizen', id: 1 }); setFollow(false); controls.current?.fit(); setExperiments(false); refresh();
  };
  useEffect(() => {
    if (!active) return;
    const key = (e: KeyboardEvent) => { const t = e.target as HTMLElement; if (t.closest('input,textarea,button,[role="dialog"],[role="alertdialog"],[role="slider"],[role="combobox"],[role="tab"],[contenteditable="true"]')) return; if (e.code === 'Space') { e.preventDefault(); engine.setPaused(!engine.paused); redraw(n => n + 1); } if (e.key === 'Escape') setFollow(false); };
    window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key);
  }, [active, engine]);
  const night = s.time % 1440 < 360 || s.time % 1440 >= 1200;
  return <SidebarProvider style={{ '--sidebar-width': '264px' } as React.CSSProperties} className="app-shell city-shell">
    <Sidebar className="observatory-sidebar"><SidebarHeader className="brand"><div className="brand-symbol"><Building2 size={24}/></div><div><strong>{tr("simulation")}<span>{tr("hub")}</span></strong><small>{tr("A SPACE FOR CURIOSITY")}</small></div><SidebarTrigger className="mobile-sidebar-close" aria-label={tr("Close city settings")}/></SidebarHeader>
      <SidebarContent><HubNavigation current="city" onNavigate={onNavigate}/><div className="sidebar-divider"/>
        <div className="sidebar-section"><div className="section-title"><Bus size={16}/><span>{tr("The Loop · public transit")}</span></div>
          <Parameter label={tr("Buses in service")} value={s.policies.buses} suffix={tr(" buses")} max={6} onChange={n => policy('buses', n)}/>
          <Parameter label={tr("Bus fare")} value={s.policies.fare} prefix="¤" max={6} onChange={n => policy('fare', n)}/>
          <p className="city-sidebar-note">{tr(s.policies.buses ? `${m.riding} aboard · ${m.waiting} waiting at stops` : 'Service is off. Residents use another way to travel.')}</p>
        </div><div className="sidebar-divider"/>
        <div className="sidebar-section"><div className="section-title"><SlidersHorizontal size={16}/><span>{tr("City policies")}</span></div>
          <Parameter label={tr("Income tax")} value={s.policies.tax} suffix={tr("%")} max={35} onChange={n => policy('tax', n)}/>
          <Parameter label={tr("Public services")} value={s.policies.services} suffix={tr("%")} max={100} step={5} onChange={n => policy('services', n)}/>
          <p className="city-sidebar-note">{tr("Services support well-being and residents without a job. Funding comes from the city treasury.")}</p>
        </div><div className="sidebar-divider"/>
        <div className="sidebar-section"><div className="section-title"><CloudRain size={16}/><span>{tr("Change the conditions")}</span></div>
          <Toggle label={tr("Rain")} checked={s.policies.rain} onChange={n => policy('rain', n)}/>
          <Toggle label={tr("Close Market Street")} checked={s.policies.roadClosed} onChange={n => policy('roadClosed', n)}/>
        </div><div className="sidebar-divider"/>
        <div className="sidebar-section"><div className="section-title"><Layers3 size={16}/><span>{tr("City details")}</span></div><Toggle label={tr("Building labels")} checked={labels} onChange={setLabels}/><Toggle label={tr("Bus route & stops")} checked={busRoute} onChange={setBusRoute}/></div>
      </SidebarContent><SidebarFooter className="sidebar-bottom"><button onClick={() => setHelp(true)}><CircleHelp size={17}/>{tr("How this city works")}<span>↗</span></button><div className="version-line"><span>{tr("CITY LIFE")}</span><span>03</span></div></SidebarFooter>
    </Sidebar>
    <main className="workspace city-workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>{tr("Simulations")}</span><ChevronRight size={14}/><strong>{tr("City Life")}</strong></div><button className="button secondary" onClick={() => setExperiments(true)}><Sparkles size={16}/>{tr("Experiments")}</button></header>
      <div className="page-heading"><div><div className="title-row"><h1>{tr("A city with ")}<span>{tr("a life of its own.")}</span></h1><span className="species-tag">{tr("LINDEN · AGENT SANDBOX")}</span></div><p>{tr("Follow a resident. Change a policy. Watch the city respond.")}</p></div><button className="icon-button" aria-label={tr("About City Life")} onClick={() => setHelp(true)}><CircleHelp size={20}/></button></div>
      {message && <div className="city-notice" role="status">{tr(message)}<button className="icon-button" aria-label={tr("Dismiss city message")} onClick={() => setMessage('')}><X size={15}/></button></div>}
      <CityWorkbench active={active} engine={engine} selection={selection} onSelect={select} onChange={refresh} onMessage={setMessage}/>
      <section className="simulation-panel city-panel" aria-label={tr("City simulation")}>
        <div className="world-topbar city-topbar"><div className="city-view-clock"><Tabs value={view} onValueChange={value => setView(value as '3d' | 'map')}><TabsList className="view-tabs city-view-tabs" aria-label={tr("City view")}><TabsTrigger value="3d" disabled={threeUnavailable}><Box size={15}/>{tr("3D city")}</TabsTrigger><TabsTrigger value="map"><Layers3 size={15}/>{tr("Map")}</TabsTrigger></TabsList></Tabs>{threeUnavailable && <button className="button secondary" onClick={() => { setMessage(''); setThreeUnavailable(false); setView('3d'); }}>{tr('Retry 3D')}</button>}<div className="city-clock">{s.policies.rain ? <CloudRain size={19}/> : <Sun size={19}/>}<div><strong>{tr(clockTime(s.time))}</strong><span>{tr("Day ")}{tr(dayNumber(s.time))} · {tr(s.policies.rain ? 'Rainy' : night ? 'Night' : 'Clear skies')}</span></div></div></div>
          <div className="playback"><button className="icon-button pause-button" aria-label={tr(engine.paused ? 'Play city simulation' : 'Pause city simulation')} onClick={() => { engine.setPaused(!engine.paused); refresh(); }}>{engine.paused ? <Play size={16}/> : <Pause size={16}/>}</button><button className="icon-button" aria-label={tr("Advance city by 15 minutes")} onClick={() => { engine.setPaused(true); engine.advance(15); refresh(); }}><SkipForward size={16}/></button><Select value={String(engine.speed)} onValueChange={n => { engine.setSpeed(Number(n)); refresh(); }}><SelectTrigger className="speed-select" aria-label={tr("City simulation speed")}><SelectValue/></SelectTrigger><SelectContent>{[1, 2, 4, 8].map(n => <SelectItem key={n} value={String(n)}>{tr(n)}{tr("× speed")}</SelectItem>)}</SelectContent></Select><button className="icon-button" aria-label={tr("Reset city")} onClick={() => setConfirm('morning')}><RotateCcw size={16}/></button></div>
        </div>
        <div className="city-stage"><div className={`city-map-wrap ${view === '3d' ? 'city-view-3d' : ''}`}>
          {!threeUnavailable && <div className="city-renderer" hidden={view !== '3d'}><Suspense fallback={<div className="city-3d-loading" role="status">{tr("Opening the 3D city…")}</div>}><CityThree engine={engine} active={active && view === '3d' && !experiments && !help && !confirm} display={{ language, layer, labels, busRoute, selection, follow }} controlsRef={threeControls} onSelect={select} onChange={refresh} onPan={() => setFollow(false)} onUnavailable={notice => { setThreeUnavailable(true); setView('map'); setMessage(notice); }}/></Suspense></div>}
          <div className="city-renderer" hidden={view !== 'map'}><CityCanvas engine={engine} active={active && view === 'map' && !experiments && !help && !confirm} display={{ language, layer, labels, busRoute, selection, follow }} controlsRef={mapControls} onSelect={select} onChange={refresh} onPan={() => setFollow(false)}/></div>
          <div className="city-map-top"><span className="city-live"><i className={engine.paused ? 'paused' : ''}/>{tr(engine.paused ? 'PAUSED' : 'LIVE CITY')}</span><Select value={layer} onValueChange={value => setLayer(value as Layer)}><SelectTrigger className="city-layer-select" aria-label={tr("City map layer")}><Layers3 size={14}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="city">{tr("City view")}</SelectItem><SelectItem value="traffic">{tr("Traffic")}</SelectItem><SelectItem value="happiness">{tr("Happiness")}</SelectItem><SelectItem value="pollution">{tr("Road emissions")}</SelectItem></SelectContent></Select></div>
          {view === '3d' && <div className="city-camera-presets" aria-label={tr('Camera presets')}>{(['overview', 'neighborhood', 'street'] as const).map(preset => <button key={preset} onClick={() => controls.current?.preset?.(preset)}>{tr(preset === 'overview' ? 'Overview' : preset === 'neighborhood' ? 'Neighborhood' : 'Street view')}</button>)}</div>}
          <div className="city-map-bottom"><span><MousePointer2 size={13}/>{tr(follow && c ? `Following ${c.name.split(' ')[0]}` : view === '3d' ? 'Drag to orbit · Shift-drag to pan · scroll to zoom' : 'Select a resident or building')}</span><div className="city-map-controls">{view === '3d' && <><button aria-label={tr("Rotate city left")} title={tr("Rotate left")} onClick={() => controls.current?.rotate?.(Math.PI / 6)}><RotateCcw size={16}/></button><button aria-label={tr("Rotate city right")} title={tr("Rotate right")} onClick={() => controls.current?.rotate?.(-Math.PI / 6)}><RotateCw size={16}/></button></>}<button aria-label={tr("Zoom in on city")} onClick={() => controls.current?.zoom(1.3)}><Plus size={16}/></button><button aria-label={tr("Zoom out of city")} onClick={() => controls.current?.zoom(1 / 1.3)}><Minus size={16}/></button><button aria-label={tr("Fit city to view")} onClick={() => controls.current?.fit()}><Focus size={16}/></button></div></div>
          <div className="city-legend">{layer === 'city' ? Object.entries(COLORS).map(([kind, color]) => <span key={kind}><i style={{ background: color }}/>{tr(kind === 'home' ? 'Homes' : kind === 'office' ? 'Work' : kind === 'shop' ? 'Shops' : kind === 'park' ? 'Parks' : kind === 'empty' ? 'Vacant plots' : 'Services')}</span>) : <span>{tr(layer === 'happiness' ? 'Home colors: green ≥ 70 · amber 50–69 · coral < 50 happiness' : layer === 'traffic' ? 'Road colors: green 0–1 · amber 2–3 · coral 4+ cars' : 'Brighter roads carry more cars · illustrative emissions')}</span>}</div>
        </div>
        <aside className="city-inspector" aria-label={tr("City inspector")}><div className="city-inspector-heading"><span className="city-kicker">{tr(b ? 'BUILDING INSPECTOR' : 'A LIFE IN LINDEN')}</span>{b && <button className="icon-button" aria-label={tr("Return to residents")} onClick={() => select({ kind: 'citizen', id: 1 })}><Users size={16}/></button>}</div>
          {c ? <><Select value={String(c.id)} onValueChange={n => select({ kind: 'citizen', id: Number(n) })}><SelectTrigger className="city-resident-select" aria-label={tr("Choose a resident")}><SelectValue/></SelectTrigger><SelectContent>{s.citizens.filter(person => person.active).map(person => <SelectItem key={person.id} value={String(person.id)}>{tr(person.name)}</SelectItem>)}</SelectContent></Select>
            <p className="city-resident-meta">{tr(c.age)}{tr(" years · ")}{tr(s.buildings[c.home].district)}</p><span className="city-activity">{tr(c.trip ? c.trip.stage === 'blocked' ? 'Waiting for road access' : c.trip.stage === 'parking' ? 'Finding parking' : c.trip.stage === 'waiting' ? 'Waiting for the bus' : c.trip.stage === 'riding' ? 'Riding the Loop' : c.trip.mode === 'car' ? 'Driving' : 'Walking' : c.activity === 'work' ? 'At work' : c.activity === 'home' ? 'At home' : c.activity === 'relaxing' ? 'In the park' : 'Shopping')}</span>
            <p className="city-reason">“{tr(c.reason)}”</p>
            <button className={`button city-follow ${follow ? 'following' : 'secondary'}`} onClick={() => setFollow(!follow)}><Target size={15}/>{tr(follow ? 'Following · stop' : 'Follow this resident')}<ArrowUpRight size={14}/></button>
            <div className="city-needs"><Need label={tr("Happiness")} value={c.happiness}/><Need label={tr("Energy")} value={c.energy}/><Need label={tr("Hunger")} value={c.hunger} warning/></div>
            <dl className="city-details"><div><dt><Wallet size={13}/>{tr("Wallet")}</dt><dd>{tr(money(c.money))}</dd></div><div><dt><MapPin size={13}/>{tr("Home")}</dt><dd><button onClick={() => select({ kind: 'building', id: c.home })}>{tr(s.buildings[c.home].name)}</button></dd></div><div><dt>{tr("Work")}</dt><dd>{tr(c.job === null ? 'Between jobs' : s.buildings[c.job].name)}</dd></div>{c.trip && <div><dt>{tr("Destination")}</dt><dd>{tr(s.buildings[c.trip.destination].name)}</dd></div>}<div><dt>{tr("Last commute")}</dt><dd>{tr(c.commute ? `${Math.round(c.commute)} min` : 'Not yet today')}</dd></div></dl>
            <details className="city-journal" open><summary>{tr("Today’s moments")}</summary>{c.log.length ? c.log.slice(0, 4).map((entry, i) => <div key={`${entry.time}-${i}`}><time>{tr(clockTime(entry.time))}</time><p>{tr(entry.text)}</p></div>) : <p>{tr("The day is just beginning. Moments appear as this resident makes decisions.")}</p>}</details>
          </> : b ? <><h2>{tr(b.name)}</h2><p className="city-resident-meta">{tr(b.district)} · {tr(b.kind === 'office' ? 'Workplace' : b.kind)}</p><div className="city-building-symbol" style={{ color: COLORS[b.kind] }}><Building2 size={42}/></div><p className="city-reason">{tr(b.kind === 'home' ? 'A place to recharge. Residents pay daily housing and household costs, then plan the next day around their work and needs.' : b.kind === 'office' || b.kind === 'shop' ? 'Workers earn wages while they are here. Their income supports daily needs and contributes to the city through tax.' : b.kind === 'park' ? 'Residents visit after errands or during free time. Time outdoors improves happiness; rain sends them home.' : 'City services contribute to well-being and support people between jobs. Adjust funding in City policies.')}</p>
            <dl className="city-details"><div><dt>{tr("Here now")}</dt><dd>{tr(s.citizens.filter(p => p.active).filter(p => !p.trip && p.location === b.id).length)}{tr(" people")}</dd></div>{b.kind === 'home' && <><div><dt>{tr("Residents")}</dt><dd>{tr(s.citizens.filter(p => p.active).filter(p => p.home === b.id).length)}</dd></div><div><dt>{tr("Household costs")}</dt><dd>{tr(`¤${Math.round(b.rent + 12)} / person / day`)}</dd></div></>}{(b.kind === 'office' || b.kind === 'shop') && <div><dt>{tr("Employees")}</dt><dd>{tr(s.citizens.filter(p => p.active).filter(p => p.job === b.id).length)}</dd></div>}</dl>
            {(b.kind === 'office' || b.kind === 'shop') && <p className="city-resident-meta">{tr(b.open ? 'Open' : 'Closed')} · {tr('Business cash')}: {money(b.cash)}</p>}
            <div className="city-building-issues">{engine.buildingIssues(b.id).length ? engine.buildingIssues(b.id).map(issue => <div key={issue.title}><strong>{tr(issue.title)}</strong><p>{tr(issue.detail)}</p>{issue.residents.slice(0, 3).map(id => <button key={id} onClick={() => select({ kind: 'citizen', id })}>{s.citizens[id].name} ↗</button>)}</div>) : <p>{tr('No urgent problems at this property.')}</p>}</div>
            <div className="city-building-residents">{s.citizens.filter(p => p.active).filter(p => b.kind === 'home' ? p.home === b.id : !p.trip && p.location === b.id).slice(0, 8).map(person => <button key={person.id} onClick={() => select({ kind: 'citizen', id: person.id })}>{tr(person.name)}<ChevronRight size={14}/></button>)}</div>
          </> : selection?.kind === 'road' || selection?.kind === 'stop' ? <p>{tr("Selected on the map. Use Build above to edit this street or stop.")}</p> : <p>{tr("Select a resident or building on the map.")}</p>}
        </aside></div>
        <div className="city-metrics"><Metric icon={<Users size={15}/>} label={tr("Residents")} value={String(m.population)} note={tr(`${m.employed} employed · ${m.population - m.employed} between jobs`)}/><Metric icon={<Heart size={15}/>} label={tr("Happiness")} value={`${Math.round(m.happiness)}%`} note={tr("Citywide well-being")}><Trend values={s.history.map(v => v.happiness)}/></Metric><Metric icon={<Footprints size={15}/>} label={tr("On the move")} value={String(m.walking + m.driving + m.riding + m.waiting)} note={tr(`${m.walking} walking · ${m.driving} driving · ${m.riding} on buses`)}/><Metric icon={<Wallet size={15}/>} label={tr("City treasury")} value={money(s.treasury)} note={tr(s.treasury < 0 ? 'Deficit · consider tax or service funding' : `${m.commute ? `${Math.round(m.commute)} min average commute` : 'Waiting for the first work arrivals'}`)}/></div>
      </section>
      <footer className="workspace-footer city-footer"><span><i className="status-dot"/>{tr(s.events[0]?.text)}</span><span>{tr(engine.paused ? 'Paused' : '8 simulated min / second at 1×')}{tr(" · Local autosave")}</span></footer>
    </main>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent className="city-dialog"><DialogHeader><DialogTitle>{tr("Small choices. A living city.")}</DialogTitle><DialogDescription>{tr("Linden is a simplified, deterministic city sandbox. It illustrates connections; it is not a forecast of a real city.")}</DialogDescription></DialogHeader><div className="city-help"><h3>{tr("Follow the day")}</h3><p>{tr("Residents leave home for work, earn wages, buy groceries, visit parks, and return to rest. Select someone on the map or use the resident picker. Their journal explains what they are doing and why.")}</p><h3>{tr("Try a change")}</h3><p>{tr("More buses and cheaper fares encourage transit. Cars slow each other down on busy roads. Rain slows travel, and a closed road changes routes. Tax funds services; services support happiness and provide daily help to people between jobs.")}</p><h3>{tr("Run an experiment")}</h3><p>{tr("Use Compare policies to capture a starting point, change sidebar policies, and run both versions for exactly the same elapsed time. Changes to transit affect the next trip; people already on their way continue unless service is withdrawn.")}</p><h3>{tr("Controls and limits")}</h3><p>{tr("The city opens in full 3D. Drag to orbit, Shift-drag or right-drag to pan, and scroll or pinch to zoom. On touch screens, one finger orbits and two fingers pan or zoom. Arrow keys pan; Shift+arrows rotate; F fits the city. Space pauses and Enter selects the next resident. Use Map for the overhead view; both views share the same live city. Labels appear when you move closer. Switching simulations suspends this city. Use Shape your city to redevelop plots, edit streets and stops, save named cities locally and compare policies from one checkpoint. Housing, hiring, rent and migration update daily. The street grid and Loop route are fixed; services and road emissions remain simplified measures. Workplaces run every day.")}</p></div></DialogContent></Dialog>
    <Dialog open={experiments} onOpenChange={setExperiments}><DialogContent className="city-dialog city-experiments"><DialogHeader><DialogTitle>{tr("What changes when…")}</DialogTitle><DialogDescription>{tr("Start with the same town and residents. Change one condition and watch what follows.")}</DialogDescription></DialogHeader><div className="city-scenarios">{scenarios.map((scenario, i) => <button key={scenario.id} onClick={() => setConfirm(scenario.id)}><span>0{tr(i + 1)}</span><div><h3>{tr(scenario.title)}</h3><p>{tr(scenario.description)}</p></div><ArrowUpRight size={18}/></button>)}</div><p className="city-sidebar-note">{tr("Use Compare policies under Shape your city for an automatic comparison from the same checkpoint.")}</p></DialogContent></Dialog>
    <AlertDialog open={confirm !== null} onOpenChange={open => { if (!open) setConfirm(null); }}><AlertDialogContent className="city-dialog"><AlertDialogHeader><AlertDialogTitle>{tr('Start a fresh morning?')}</AlertDialogTitle><AlertDialogDescription>{tr('The current city will restart at 07:00. Named local saves remain available.')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{tr("Keep exploring")}</AlertDialogCancel><AlertDialogAction onClick={() => { if (confirm) reset(confirm); setConfirm(null); }}>{tr('Start scenario')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </SidebarProvider>;
}
function Parameter({ label, value, max, onChange, prefix = '', suffix = '', step = 1 }: { label: string; value: number; max: number; onChange: (n: number) => void; prefix?: string; suffix?: string; step?: number }) {
 const tr = useT(); return <div className="parameter city-parameter"><div><label>{tr(label)}</label><output>{tr(prefix)}{tr(value)}{tr(suffix)}</output></div><Slider aria-label={tr(label)} value={[value]} min={0} max={max} step={step} onValueChange={values => onChange(values[0])}/></div>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) {
 const tr = useT(); return <label className="layer-toggle city-toggle"><span>{tr(label)}</span><Switch aria-label={tr(label)} checked={checked} onCheckedChange={onChange}/></label>; }
function Need({ label, value, warning = false }: { label: string; value: number; warning?: boolean }) {
 const tr = useT(); return <div className={`city-need ${warning ? 'hunger' : ''}`}><div><span>{tr(label)}</span><output>{tr(Math.round(value))}%</output></div><Progress value={value} aria-label={tr(label)}/></div>; }
function Metric({ icon, label, value, note, children }: { icon: React.ReactNode; label: string; value: string; note: string; children?: React.ReactNode }) {
 const tr = useT(); return <div className="city-metric"><span>{tr(icon)}{tr(label)}</span><div><strong>{tr(value)}</strong>{tr(children)}</div><p>{tr(note)}</p></div>; }
function Trend({ values }: { values: number[] }) {
 const tr = useT(); const recent = values.slice(-48); return <svg className="city-trend" viewBox="0 0 100 32" aria-label={tr("Happiness history")} role="img"><polyline fill="none" stroke="currentColor" strokeWidth="1.5" points={recent.map((n, i) => `${i / Math.max(1, recent.length - 1) * 100},${31 - n * .3}`).join(' ')}/></svg>; }
